-- +goose Up
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    openid VARCHAR(128) NOT NULL UNIQUE,
    nickname VARCHAR(120) NOT NULL DEFAULT '',
    avatar_url TEXT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT users_openid_not_blank CHECK (BTRIM(openid) <> ''),
    CONSTRAINT users_status_check CHECK (status IN ('active', 'frozen'))
);

CREATE TABLE admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role VARCHAR(24) NOT NULL DEFAULT 'admin',
    status VARCHAR(16) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT admin_users_username_not_blank CHECK (BTRIM(username) <> ''),
    CONSTRAINT admin_users_role_check CHECK (role IN ('admin', 'super_admin')),
    CONSTRAINT admin_users_status_check CHECK (status IN ('active', 'frozen'))
);

CREATE TABLE teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description TEXT NULL,
    logo_url TEXT NULL,
    captain_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT teams_name_not_blank CHECK (BTRIM(name) <> ''),
    CONSTRAINT teams_status_check CHECK (status IN ('active', 'frozen'))
);

CREATE TABLE team_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role VARCHAR(24) NOT NULL DEFAULT 'member',
    status VARCHAR(16) NOT NULL DEFAULT 'active',
    joined_at TIMESTAMP NOT NULL DEFAULT NOW(),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT team_members_team_user_unique UNIQUE (team_id, user_id),
    CONSTRAINT team_members_role_check CHECK (role IN ('captain', 'leader', 'vice_captain', 'member')),
    CONSTRAINT team_members_status_check CHECK (status IN ('active', 'inactive'))
);

CREATE INDEX team_members_user_active_idx
    ON team_members (user_id, team_id)
    WHERE status = 'active';

CREATE TABLE matches (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    publication_mode VARCHAR(32) NOT NULL,
    opponent_state VARCHAR(32) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'registering',
    host_team_id BIGINT NOT NULL REFERENCES teams(id),
    away_team_id BIGINT NULL REFERENCES teams(id),
    opponent_name VARCHAR(255) NULL,
    players_per_team INTEGER NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    location VARCHAR(255) NOT NULL,
    location_latitude DOUBLE PRECISION NULL,
    location_longitude DOUBLE PRECISION NULL,
    description TEXT NULL,
    created_by_user_id BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT matches_name_not_blank CHECK (BTRIM(name) <> ''),
    CONSTRAINT matches_location_not_blank CHECK (BTRIM(location) <> ''),
    CONSTRAINT matches_publication_mode_check CHECK (publication_mode IN ('offline_confirmed', 'online_team', 'online_individual')),
    CONSTRAINT matches_opponent_state_check CHECK (opponent_state IN ('no_recruitment', 'recruiting', 'confirmed')),
    CONSTRAINT matches_status_check CHECK (status IN ('registering', 'ongoing', 'ended', 'cancelled')),
    CONSTRAINT matches_players_per_team_positive CHECK (players_per_team > 0),
    CONSTRAINT matches_time_order_check CHECK (end_time > start_time),
    CONSTRAINT matches_teams_different_check CHECK (away_team_id IS NULL OR away_team_id <> host_team_id),
    CONSTRAINT matches_coordinates_pair_check CHECK ((location_latitude IS NULL) = (location_longitude IS NULL)),
    CONSTRAINT matches_offline_fields_check CHECK (
        (
            publication_mode = 'offline_confirmed'
            AND opponent_name IS NOT NULL
            AND BTRIM(opponent_name) <> ''
            AND opponent_state = 'no_recruitment'
            AND away_team_id IS NULL
        )
        OR
        (
            publication_mode <> 'offline_confirmed'
            AND opponent_name IS NULL
            AND opponent_state IN ('recruiting', 'confirmed')
        )
    )
);

CREATE INDEX matches_start_time_idx ON matches (start_time DESC, id);
CREATE INDEX matches_host_team_idx ON matches (host_team_id, start_time DESC);
CREATE INDEX matches_away_team_idx ON matches (away_team_id, start_time DESC) WHERE away_team_id IS NOT NULL;
CREATE INDEX matches_recruiting_idx ON matches (publication_mode, start_time) WHERE opponent_state = 'recruiting';

CREATE TABLE match_registration_groups (
    id UUID PRIMARY KEY,
    match_id UUID NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
    kind VARCHAR(32) NOT NULL,
    team_id BIGINT NULL REFERENCES teams(id),
    min_players INTEGER NULL,
    max_players INTEGER NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'open',
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    cancelled_at TIMESTAMP NULL,
    CONSTRAINT match_registration_groups_kind_check CHECK (kind IN ('host_team', 'guest_team', 'individual_opponent')),
    CONSTRAINT match_registration_groups_status_check CHECK (status IN ('open', 'closed', 'cancelled')),
    CONSTRAINT match_registration_groups_limits_check CHECK (
        (min_players IS NULL OR min_players > 0)
        AND (max_players IS NULL OR max_players > 0)
        AND (min_players IS NULL OR max_players IS NULL OR min_players <= max_players)
    ),
    CONSTRAINT match_registration_groups_shape_check CHECK (
        (
            kind IN ('host_team', 'guest_team')
            AND team_id IS NOT NULL
            AND min_players IS NULL
        )
        OR
        (
            kind = 'individual_opponent'
            AND team_id IS NULL
            AND min_players IS NOT NULL
            AND max_players IS NOT NULL
        )
    ),
    CONSTRAINT match_registration_groups_cancelled_at_check CHECK (
        (status = 'cancelled' AND cancelled_at IS NOT NULL)
        OR (status <> 'cancelled' AND cancelled_at IS NULL)
    )
);

CREATE UNIQUE INDEX match_registration_groups_active_kind_unique
    ON match_registration_groups (match_id, kind)
    WHERE status <> 'cancelled';

CREATE UNIQUE INDEX match_registration_groups_active_team_unique
    ON match_registration_groups (match_id, team_id)
    WHERE status <> 'cancelled' AND team_id IS NOT NULL;

CREATE TABLE match_registrations (
    id UUID PRIMARY KEY,
    group_id UUID NOT NULL REFERENCES match_registration_groups(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(16) NOT NULL DEFAULT 'attending',
    registration_count INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    cancelled_at TIMESTAMP NULL,
    CONSTRAINT match_registrations_group_user_unique UNIQUE (group_id, user_id),
    CONSTRAINT match_registrations_status_check CHECK (status IN ('attending', 'leave', 'absent', 'cancelled')),
    CONSTRAINT match_registrations_count_positive CHECK (registration_count > 0),
    CONSTRAINT match_registrations_cancelled_at_check CHECK (
        (status = 'cancelled' AND cancelled_at IS NOT NULL)
        OR (status <> 'cancelled' AND cancelled_at IS NULL)
    )
);

CREATE INDEX match_registrations_group_active_idx
    ON match_registrations (group_id, created_at)
    WHERE status <> 'cancelled';

CREATE TABLE match_team_applications (
    id UUID PRIMARY KEY,
    match_id UUID NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
    applicant_team_id BIGINT NOT NULL REFERENCES teams(id),
    introduction TEXT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'pending',
    created_by_user_id BIGINT NOT NULL REFERENCES users(id),
    selected_at TIMESTAMP NULL,
    withdrawn_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT match_team_applications_introduction_not_blank CHECK (BTRIM(introduction) <> ''),
    CONSTRAINT match_team_applications_status_check CHECK (status IN ('pending', 'selected', 'rejected', 'withdrawn')),
    CONSTRAINT match_team_applications_timestamps_check CHECK (
        (status = 'selected' AND selected_at IS NOT NULL AND withdrawn_at IS NULL)
        OR (status = 'withdrawn' AND withdrawn_at IS NOT NULL)
        OR (status IN ('pending', 'rejected') AND selected_at IS NULL AND withdrawn_at IS NULL)
    )
);

CREATE UNIQUE INDEX match_team_applications_active_team_unique
    ON match_team_applications (match_id, applicant_team_id)
    WHERE status IN ('pending', 'selected');

CREATE UNIQUE INDEX match_team_applications_selected_unique
    ON match_team_applications (match_id)
    WHERE status = 'selected';

CREATE TABLE match_registration_defaults (
    players_per_team INTEGER PRIMARY KEY,
    min_players INTEGER NOT NULL,
    max_players INTEGER NOT NULL,
    updated_by_admin_id BIGINT NULL REFERENCES admin_users(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT match_registration_defaults_players_positive CHECK (players_per_team > 0),
    CONSTRAINT match_registration_defaults_limits_check CHECK (min_players > 0 AND max_players > 0 AND min_players <= max_players)
);

-- +goose Down
DROP TABLE IF EXISTS match_registration_defaults;
DROP TABLE IF EXISTS match_team_applications;
DROP TABLE IF EXISTS match_registrations;
DROP TABLE IF EXISTS match_registration_groups;
DROP TABLE IF EXISTS matches;
DROP TABLE IF EXISTS team_members;
DROP TABLE IF EXISTS teams;
DROP TABLE IF EXISTS admin_users;
DROP TABLE IF EXISTS users;
