-- +goose Up
-- web-view 一次性登录 code：小程序登录态换取 web-view 会话，仅存 SHA-256 哈希。
CREATE TABLE auth_webview_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    code_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX auth_webview_codes_hash_idx ON auth_webview_codes (code_hash);
CREATE INDEX auth_webview_codes_user_idx ON auth_webview_codes (user_id, id DESC);

-- +goose Down
DROP TABLE IF EXISTS auth_webview_codes;
