-- +goose Up
-- 队费记账：比赛结算批次与队费流水。余额沿用 team_members.balance_cents；
-- 流水从本迁移上线起记录，历史队费充值不回填。

CREATE TABLE match_settlement_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id UUID NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
    batch_no INT NOT NULL,
    operation_type VARCHAR(16) NOT NULL,
    reversal_of_batch_id BIGINT NULL REFERENCES match_settlement_batches(id),
    reversed_by_batch_id BIGINT NULL REFERENCES match_settlement_batches(id),
    description TEXT NOT NULL DEFAULT '',
    total_amount_cents BIGINT NOT NULL,
    user_count INT NOT NULL,
    created_by_user_id BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT match_settlement_batches_type_check CHECK (operation_type IN ('settle', 'reverse')),
    CONSTRAINT match_settlement_batches_batch_no_positive CHECK (batch_no > 0),
    CONSTRAINT match_settlement_batches_user_count_check CHECK (user_count >= 0),
    CONSTRAINT match_settlement_batches_reverse_link_check CHECK (
        (operation_type = 'settle' AND reversal_of_batch_id IS NULL)
        OR (operation_type = 'reverse' AND reversal_of_batch_id IS NOT NULL)
    ),
    CONSTRAINT match_settlement_batches_match_batch_unique UNIQUE (match_id, batch_no)
);

-- 每场比赛至多一个未冲正的 settle 批次，兜底并发结算。
CREATE UNIQUE INDEX match_settlement_batches_active_unique
    ON match_settlement_batches (match_id)
    WHERE operation_type = 'settle' AND reversed_by_batch_id IS NULL;

CREATE TABLE team_fund_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    amount_cents BIGINT NOT NULL,
    balance_after_cents BIGINT NOT NULL,
    source VARCHAR(32) NOT NULL,
    source_id VARCHAR(64) NOT NULL,
    match_id UUID NULL REFERENCES matches(id) ON DELETE SET NULL,
    description TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT team_fund_transactions_source_check CHECK (
        source IN ('membership_payment', 'match_settlement', 'settlement_reversal')
    ),
    CONSTRAINT team_fund_transactions_source_unique UNIQUE (source, source_id, user_id)
);

CREATE INDEX team_fund_transactions_user_idx ON team_fund_transactions (user_id, id DESC);
CREATE INDEX team_fund_transactions_team_user_idx ON team_fund_transactions (team_id, user_id, id DESC);
CREATE INDEX team_fund_transactions_match_idx ON team_fund_transactions (match_id) WHERE match_id IS NOT NULL;

-- +goose Down
DROP TABLE IF EXISTS team_fund_transactions;
DROP TABLE IF EXISTS match_settlement_batches;
