// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package teamfundsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminUser struct {
	ID           int64            `json:"id"`
	Username     string           `json:"username"`
	PasswordHash string           `json:"password_hash"`
	Role         string           `json:"role"`
	Status       string           `json:"status"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type AuthWebviewCode struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type LegacyImportMapping struct {
	SourceSystem       string             `json:"source_system"`
	EntityType         string             `json:"entity_type"`
	SourceID           string             `json:"source_id"`
	TargetID           string             `json:"target_id"`
	SourceUpdatedAt    pgtype.Timestamptz `json:"source_updated_at"`
	SourceFingerprint  string             `json:"source_fingerprint"`
	TargetFingerprint  string             `json:"target_fingerprint"`
	FingerprintVersion int32              `json:"fingerprint_version"`
	MigratedAt         pgtype.Timestamptz `json:"migrated_at"`
}

type Match struct {
	ID                  pgtype.UUID      `json:"id"`
	Name                string           `json:"name"`
	PublicationMode     string           `json:"publication_mode"`
	OpponentState       string           `json:"opponent_state"`
	Status              string           `json:"status"`
	HostTeamID          *int64           `json:"host_team_id"`
	AwayTeamID          *int64           `json:"away_team_id"`
	OpponentName        *string          `json:"opponent_name"`
	PlayersPerTeam      int32            `json:"players_per_team"`
	StartTime           pgtype.Timestamp `json:"start_time"`
	EndTime             pgtype.Timestamp `json:"end_time"`
	Location            string           `json:"location"`
	LocationLatitude    *float64         `json:"location_latitude"`
	LocationLongitude   *float64         `json:"location_longitude"`
	Description         *string          `json:"description"`
	CreatedByUserID     *int64           `json:"created_by_user_id"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	CreatedByAdminID    *int64           `json:"created_by_admin_id"`
	RegistrationStartAt pgtype.Timestamp `json:"registration_start_at"`
	RegistrationEndAt   pgtype.Timestamp `json:"registration_end_at"`
	IsFree              bool             `json:"is_free"`
	HostColor           *string          `json:"host_color"`
	AwayColor           *string          `json:"away_color"`
	PaymentMode         string           `json:"payment_mode"`
	FeePerPersonCents   int64            `json:"fee_per_person_cents"`
	HostScore           *int32           `json:"host_score"`
	AwayScore           *int32           `json:"away_score"`
}

type MatchCaptainMessage struct {
	ID                pgtype.UUID        `json:"id"`
	MatchID           pgtype.UUID        `json:"match_id"`
	TeamID            int64              `json:"team_id"`
	ThreadOwnerUserID int64              `json:"thread_owner_user_id"`
	SenderUserID      int64              `json:"sender_user_id"`
	Content           string             `json:"content"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type MatchCaptainThreadRead struct {
	ThreadID   pgtype.UUID        `json:"thread_id"`
	UserID     int64              `json:"user_id"`
	LastReadAt pgtype.Timestamptz `json:"last_read_at"`
}

type MatchRegistration struct {
	ID                pgtype.UUID      `json:"id"`
	GroupID           pgtype.UUID      `json:"group_id"`
	UserID            int64            `json:"user_id"`
	Status            string           `json:"status"`
	RegistrationCount int32            `json:"registration_count"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	CancelledAt       pgtype.Timestamp `json:"cancelled_at"`
	Paid              bool             `json:"paid"`
}

type MatchRegistrationDefault struct {
	PlayersPerTeam   int32            `json:"players_per_team"`
	MinPlayers       int32            `json:"min_players"`
	MaxPlayers       int32            `json:"max_players"`
	UpdatedByAdminID *int64           `json:"updated_by_admin_id"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

type MatchRegistrationGroup struct {
	ID          pgtype.UUID      `json:"id"`
	MatchID     pgtype.UUID      `json:"match_id"`
	Kind        string           `json:"kind"`
	TeamID      *int64           `json:"team_id"`
	MinPlayers  *int32           `json:"min_players"`
	MaxPlayers  *int32           `json:"max_players"`
	Status      string           `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	CancelledAt pgtype.Timestamp `json:"cancelled_at"`
}

type MatchSettlementBatch struct {
	ID                int64              `json:"id"`
	MatchID           pgtype.UUID        `json:"match_id"`
	BatchNo           int32              `json:"batch_no"`
	OperationType     string             `json:"operation_type"`
	ReversalOfBatchID *int64             `json:"reversal_of_batch_id"`
	ReversedByBatchID *int64             `json:"reversed_by_batch_id"`
	Description       string             `json:"description"`
	TotalAmountCents  int64              `json:"total_amount_cents"`
	UserCount         int32              `json:"user_count"`
	CreatedByUserID   int64              `json:"created_by_user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type MatchTeamApplication struct {
	ID              pgtype.UUID      `json:"id"`
	MatchID         pgtype.UUID      `json:"match_id"`
	ApplicantTeamID int64            `json:"applicant_team_id"`
	Introduction    string           `json:"introduction"`
	Status          string           `json:"status"`
	CreatedByUserID int64            `json:"created_by_user_id"`
	SelectedAt      pgtype.Timestamp `json:"selected_at"`
	WithdrawnAt     pgtype.Timestamp `json:"withdrawn_at"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type MiniAppSetting struct {
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type MiniReviewStatus struct {
	ID          int64              `json:"id"`
	ProjectCode string             `json:"project_code"`
	Version     string             `json:"version"`
	VersionCode int64              `json:"version_code"`
	IsReviewing bool               `json:"is_reviewing"`
	StatusText  string             `json:"status_text"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Notification struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	Kind        string             `json:"kind"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	RelatedType *string            `json:"related_type"`
	RelatedID   *string            `json:"related_id"`
	ReadAt      pgtype.Timestamptz `json:"read_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PaymentOrder struct {
	OrderNo       string             `json:"order_no"`
	UserID        int64              `json:"user_id"`
	AmountCents   int64              `json:"amount_cents"`
	Provider      string             `json:"provider"`
	Channel       string             `json:"channel"`
	Status        string             `json:"status"`
	PrepayID      *string            `json:"prepay_id"`
	TransactionID *string            `json:"transaction_id"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	CancelledAt   pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Kind          string             `json:"kind"`
	TeamID        *int64             `json:"team_id"`
	Months        *int32             `json:"months"`
	MatchID       pgtype.UUID        `json:"match_id"`
}

type Team struct {
	ID               int64              `json:"id"`
	Name             string             `json:"name"`
	Description      *string            `json:"description"`
	LogoUrl          *string            `json:"logo_url"`
	CaptainID        *int64             `json:"captain_id"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamp   `json:"created_at"`
	UpdatedAt        pgtype.Timestamp   `json:"updated_at"`
	CreditScore      int32              `json:"credit_score"`
	VipUntil         pgtype.Timestamptz `json:"vip_until"`
	JoinPasswordHash *string            `json:"join_password_hash"`
}

type TeamFundTransaction struct {
	ID                int64              `json:"id"`
	TeamID            int64              `json:"team_id"`
	UserID            int64              `json:"user_id"`
	AmountCents       int64              `json:"amount_cents"`
	BalanceAfterCents int64              `json:"balance_after_cents"`
	Source            string             `json:"source"`
	SourceID          string             `json:"source_id"`
	MatchID           pgtype.UUID        `json:"match_id"`
	Description       string             `json:"description"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type TeamMember struct {
	ID           int64            `json:"id"`
	TeamID       int64            `json:"team_id"`
	UserID       int64            `json:"user_id"`
	Role         string           `json:"role"`
	Status       string           `json:"status"`
	JoinedAt     pgtype.Timestamp `json:"joined_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	BalanceCents int64            `json:"balance_cents"`
}

type Tip struct {
	ID          int64              `json:"id"`
	OrderNo     string             `json:"order_no"`
	UserID      int64              `json:"user_id"`
	Nickname    string             `json:"nickname"`
	AmountCents int64              `json:"amount_cents"`
	Suggestion  string             `json:"suggestion"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	SubmittedAt pgtype.Timestamptz `json:"submitted_at"`
}

type User struct {
	ID           int64            `json:"id"`
	Openid       string           `json:"openid"`
	Nickname     string           `json:"nickname"`
	AvatarUrl    *string          `json:"avatar_url"`
	Status       string           `json:"status"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	RealName     *string          `json:"real_name"`
	PhoneNumber  *string          `json:"phone_number"`
	IsMatchAdmin bool             `json:"is_match_admin"`
}

type WalletAccount struct {
	UserID              int64              `json:"user_id"`
	BalanceCents        int64              `json:"balance_cents"`
	TotalRechargedCents int64              `json:"total_recharged_cents"`
	TotalSpentCents     int64              `json:"total_spent_cents"`
	Version             int64              `json:"version"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type WalletTransaction struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            int64              `json:"user_id"`
	Direction         string             `json:"direction"`
	Type              string             `json:"type"`
	AmountCents       int64              `json:"amount_cents"`
	BalanceAfterCents int64              `json:"balance_after_cents"`
	SourceType        string             `json:"source_type"`
	SourceID          string             `json:"source_id"`
	Description       string             `json:"description"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}
