// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet.sql

package walletsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countWalletTransactions = `-- name: CountWalletTransactions :one
SELECT COUNT(*) FROM wallet_transactions WHERE user_id = $1
`

func (q *Queries) CountWalletTransactions(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countWalletTransactions, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const debitWalletAccount = `-- name: DebitWalletAccount :one
UPDATE wallet_accounts
SET balance_cents = balance_cents - $2,
    total_spent_cents = total_spent_cents + $2,
    version = version + 1,
    updated_at = NOW()
WHERE user_id = $1 AND balance_cents >= $2
RETURNING user_id, balance_cents, total_recharged_cents, total_spent_cents, version, created_at, updated_at
`

type DebitWalletAccountParams struct {
	UserID       int64 `json:"user_id"`
	BalanceCents int64 `json:"balance_cents"`
}

func (q *Queries) DebitWalletAccount(ctx context.Context, arg DebitWalletAccountParams) (WalletAccount, error) {
	row := q.db.QueryRow(ctx, debitWalletAccount, arg.UserID, arg.BalanceCents)
	var i WalletAccount
	err := row.Scan(
		&i.UserID,
		&i.BalanceCents,
		&i.TotalRechargedCents,
		&i.TotalSpentCents,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureDebitWalletAccount = `-- name: EnsureDebitWalletAccount :one
INSERT INTO wallet_accounts (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO UPDATE SET user_id = EXCLUDED.user_id
RETURNING user_id, balance_cents, total_recharged_cents, total_spent_cents, version, created_at, updated_at
`

func (q *Queries) EnsureDebitWalletAccount(ctx context.Context, userID int64) (WalletAccount, error) {
	row := q.db.QueryRow(ctx, ensureDebitWalletAccount, userID)
	var i WalletAccount
	err := row.Scan(
		&i.UserID,
		&i.BalanceCents,
		&i.TotalRechargedCents,
		&i.TotalSpentCents,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDebitWalletAccountForUpdate = `-- name: GetDebitWalletAccountForUpdate :one
SELECT user_id, balance_cents, total_recharged_cents, total_spent_cents, version, created_at, updated_at FROM wallet_accounts WHERE user_id = $1 FOR UPDATE
`

func (q *Queries) GetDebitWalletAccountForUpdate(ctx context.Context, userID int64) (WalletAccount, error) {
	row := q.db.QueryRow(ctx, getDebitWalletAccountForUpdate, userID)
	var i WalletAccount
	err := row.Scan(
		&i.UserID,
		&i.BalanceCents,
		&i.TotalRechargedCents,
		&i.TotalSpentCents,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletAccount = `-- name: GetWalletAccount :one
SELECT user_id, balance_cents, total_recharged_cents, total_spent_cents, version, created_at, updated_at FROM wallet_accounts WHERE user_id = $1
`

func (q *Queries) GetWalletAccount(ctx context.Context, userID int64) (WalletAccount, error) {
	row := q.db.QueryRow(ctx, getWalletAccount, userID)
	var i WalletAccount
	err := row.Scan(
		&i.UserID,
		&i.BalanceCents,
		&i.TotalRechargedCents,
		&i.TotalSpentCents,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletTransactionBySource = `-- name: GetWalletTransactionBySource :one
SELECT id, user_id, direction, type, amount_cents, balance_after_cents, source_type, source_id, description, created_at FROM wallet_transactions WHERE source_type = $1 AND source_id = $2
`

type GetWalletTransactionBySourceParams struct {
	SourceType string `json:"source_type"`
	SourceID   string `json:"source_id"`
}

func (q *Queries) GetWalletTransactionBySource(ctx context.Context, arg GetWalletTransactionBySourceParams) (WalletTransaction, error) {
	row := q.db.QueryRow(ctx, getWalletTransactionBySource, arg.SourceType, arg.SourceID)
	var i WalletTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Direction,
		&i.Type,
		&i.AmountCents,
		&i.BalanceAfterCents,
		&i.SourceType,
		&i.SourceID,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const insertDebitWalletTransaction = `-- name: InsertDebitWalletTransaction :one
INSERT INTO wallet_transactions (
    id, user_id, direction, type, amount_cents, balance_after_cents,
    source_type, source_id, description
) VALUES ($1, $2, 'debit', 'spend', $3, $4, $5, $6, $7)
RETURNING id, user_id, direction, type, amount_cents, balance_after_cents, source_type, source_id, description, created_at
`

type InsertDebitWalletTransactionParams struct {
	ID                pgtype.UUID `json:"id"`
	UserID            int64       `json:"user_id"`
	AmountCents       int64       `json:"amount_cents"`
	BalanceAfterCents int64       `json:"balance_after_cents"`
	SourceType        string      `json:"source_type"`
	SourceID          string      `json:"source_id"`
	Description       string      `json:"description"`
}

func (q *Queries) InsertDebitWalletTransaction(ctx context.Context, arg InsertDebitWalletTransactionParams) (WalletTransaction, error) {
	row := q.db.QueryRow(ctx, insertDebitWalletTransaction,
		arg.ID,
		arg.UserID,
		arg.AmountCents,
		arg.BalanceAfterCents,
		arg.SourceType,
		arg.SourceID,
		arg.Description,
	)
	var i WalletTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Direction,
		&i.Type,
		&i.AmountCents,
		&i.BalanceAfterCents,
		&i.SourceType,
		&i.SourceID,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listWalletTransactions = `-- name: ListWalletTransactions :many
SELECT id, user_id, direction, type, amount_cents, balance_after_cents, source_type, source_id, description, created_at FROM wallet_transactions
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListWalletTransactionsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListWalletTransactions(ctx context.Context, arg ListWalletTransactionsParams) ([]WalletTransaction, error) {
	rows, err := q.db.Query(ctx, listWalletTransactions, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WalletTransaction
	for rows.Next() {
		var i WalletTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Direction,
			&i.Type,
			&i.AmountCents,
			&i.BalanceAfterCents,
			&i.SourceType,
			&i.SourceID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
