// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package paymentsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelPaymentOrder = `-- name: CancelPaymentOrder :one
UPDATE payment_orders
SET status = 'cancelled', cancelled_at = $2, updated_at = $2
WHERE order_no = $1 AND status = 'pending'
RETURNING order_no, user_id, amount_cents, provider, channel, status, prepay_id, transaction_id, paid_at, cancelled_at, created_at, updated_at
`

type CancelPaymentOrderParams struct {
	OrderNo     string             `json:"order_no"`
	CancelledAt pgtype.Timestamptz `json:"cancelled_at"`
}

func (q *Queries) CancelPaymentOrder(ctx context.Context, arg CancelPaymentOrderParams) (PaymentOrder, error) {
	row := q.db.QueryRow(ctx, cancelPaymentOrder, arg.OrderNo, arg.CancelledAt)
	var i PaymentOrder
	err := row.Scan(
		&i.OrderNo,
		&i.UserID,
		&i.AmountCents,
		&i.Provider,
		&i.Channel,
		&i.Status,
		&i.PrepayID,
		&i.TransactionID,
		&i.PaidAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countPaymentOrders = `-- name: CountPaymentOrders :one
SELECT COUNT(*) FROM payment_orders
WHERE ($1::bigint = 0 OR user_id = $1)
  AND ($2::text = '' OR status = $2)
  AND ($3::text = '' OR order_no ILIKE '%' || $3 || '%')
`

type CountPaymentOrdersParams struct {
	UserID int64  `json:"user_id"`
	Status string `json:"status"`
	Search string `json:"search"`
}

func (q *Queries) CountPaymentOrders(ctx context.Context, arg CountPaymentOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentOrders, arg.UserID, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPaymentOrder = `-- name: CreatePaymentOrder :one
INSERT INTO payment_orders (
    order_no, user_id, amount_cents, provider, channel, status, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $7)
RETURNING order_no, user_id, amount_cents, provider, channel, status, prepay_id, transaction_id, paid_at, cancelled_at, created_at, updated_at
`

type CreatePaymentOrderParams struct {
	OrderNo     string             `json:"order_no"`
	UserID      int64              `json:"user_id"`
	AmountCents int64              `json:"amount_cents"`
	Provider    string             `json:"provider"`
	Channel     string             `json:"channel"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreatePaymentOrder(ctx context.Context, arg CreatePaymentOrderParams) (PaymentOrder, error) {
	row := q.db.QueryRow(ctx, createPaymentOrder,
		arg.OrderNo,
		arg.UserID,
		arg.AmountCents,
		arg.Provider,
		arg.Channel,
		arg.Status,
		arg.CreatedAt,
	)
	var i PaymentOrder
	err := row.Scan(
		&i.OrderNo,
		&i.UserID,
		&i.AmountCents,
		&i.Provider,
		&i.Channel,
		&i.Status,
		&i.PrepayID,
		&i.TransactionID,
		&i.PaidAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const creditRechargeWallet = `-- name: CreditRechargeWallet :one
UPDATE wallet_accounts
SET balance_cents = balance_cents + $2,
    total_recharged_cents = total_recharged_cents + $2,
    version = version + 1,
    updated_at = $3
WHERE user_id = $1
RETURNING user_id, balance_cents, total_recharged_cents, total_spent_cents, version, created_at, updated_at
`

type CreditRechargeWalletParams struct {
	UserID       int64              `json:"user_id"`
	BalanceCents int64              `json:"balance_cents"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreditRechargeWallet(ctx context.Context, arg CreditRechargeWalletParams) (WalletAccount, error) {
	row := q.db.QueryRow(ctx, creditRechargeWallet, arg.UserID, arg.BalanceCents, arg.UpdatedAt)
	var i WalletAccount
	err := row.Scan(
		&i.UserID,
		&i.BalanceCents,
		&i.TotalRechargedCents,
		&i.TotalSpentCents,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureRechargeWalletAccount = `-- name: EnsureRechargeWalletAccount :one
INSERT INTO wallet_accounts (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO UPDATE SET user_id = EXCLUDED.user_id
RETURNING user_id, balance_cents, total_recharged_cents, total_spent_cents, version, created_at, updated_at
`

func (q *Queries) EnsureRechargeWalletAccount(ctx context.Context, userID int64) (WalletAccount, error) {
	row := q.db.QueryRow(ctx, ensureRechargeWalletAccount, userID)
	var i WalletAccount
	err := row.Scan(
		&i.UserID,
		&i.BalanceCents,
		&i.TotalRechargedCents,
		&i.TotalSpentCents,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentOrder = `-- name: GetPaymentOrder :one
SELECT order_no, user_id, amount_cents, provider, channel, status, prepay_id, transaction_id, paid_at, cancelled_at, created_at, updated_at FROM payment_orders WHERE order_no = $1
`

func (q *Queries) GetPaymentOrder(ctx context.Context, orderNo string) (PaymentOrder, error) {
	row := q.db.QueryRow(ctx, getPaymentOrder, orderNo)
	var i PaymentOrder
	err := row.Scan(
		&i.OrderNo,
		&i.UserID,
		&i.AmountCents,
		&i.Provider,
		&i.Channel,
		&i.Status,
		&i.PrepayID,
		&i.TransactionID,
		&i.PaidAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentOrderForUpdate = `-- name: GetPaymentOrderForUpdate :one
SELECT order_no, user_id, amount_cents, provider, channel, status, prepay_id, transaction_id, paid_at, cancelled_at, created_at, updated_at FROM payment_orders WHERE order_no = $1 FOR UPDATE
`

func (q *Queries) GetPaymentOrderForUpdate(ctx context.Context, orderNo string) (PaymentOrder, error) {
	row := q.db.QueryRow(ctx, getPaymentOrderForUpdate, orderNo)
	var i PaymentOrder
	err := row.Scan(
		&i.OrderNo,
		&i.UserID,
		&i.AmountCents,
		&i.Provider,
		&i.Channel,
		&i.Status,
		&i.PrepayID,
		&i.TransactionID,
		&i.PaidAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentUserOpenID = `-- name: GetPaymentUserOpenID :one
SELECT openid FROM users WHERE id = $1 AND status = 'active'
`

func (q *Queries) GetPaymentUserOpenID(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, getPaymentUserOpenID, id)
	var openid string
	err := row.Scan(&openid)
	return openid, err
}

const getRechargeWalletAccountForUpdate = `-- name: GetRechargeWalletAccountForUpdate :one
SELECT user_id, balance_cents, total_recharged_cents, total_spent_cents, version, created_at, updated_at FROM wallet_accounts WHERE user_id = $1 FOR UPDATE
`

func (q *Queries) GetRechargeWalletAccountForUpdate(ctx context.Context, userID int64) (WalletAccount, error) {
	row := q.db.QueryRow(ctx, getRechargeWalletAccountForUpdate, userID)
	var i WalletAccount
	err := row.Scan(
		&i.UserID,
		&i.BalanceCents,
		&i.TotalRechargedCents,
		&i.TotalSpentCents,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRechargeWalletTransaction = `-- name: InsertRechargeWalletTransaction :one
INSERT INTO wallet_transactions (
    id, user_id, direction, type, amount_cents, balance_after_cents,
    source_type, source_id, description, created_at
) VALUES ($1, $2, 'credit', 'recharge', $3, $4, 'payment_order', $5, $6, $7)
ON CONFLICT (source_type, source_id) DO NOTHING
RETURNING id, user_id, direction, type, amount_cents, balance_after_cents, source_type, source_id, description, created_at
`

type InsertRechargeWalletTransactionParams struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            int64              `json:"user_id"`
	AmountCents       int64              `json:"amount_cents"`
	BalanceAfterCents int64              `json:"balance_after_cents"`
	SourceID          string             `json:"source_id"`
	Description       string             `json:"description"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertRechargeWalletTransaction(ctx context.Context, arg InsertRechargeWalletTransactionParams) (WalletTransaction, error) {
	row := q.db.QueryRow(ctx, insertRechargeWalletTransaction,
		arg.ID,
		arg.UserID,
		arg.AmountCents,
		arg.BalanceAfterCents,
		arg.SourceID,
		arg.Description,
		arg.CreatedAt,
	)
	var i WalletTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Direction,
		&i.Type,
		&i.AmountCents,
		&i.BalanceAfterCents,
		&i.SourceType,
		&i.SourceID,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listPaymentOrders = `-- name: ListPaymentOrders :many
SELECT order_no, user_id, amount_cents, provider, channel, status, prepay_id, transaction_id, paid_at, cancelled_at, created_at, updated_at FROM payment_orders
WHERE ($1::bigint = 0 OR user_id = $1)
  AND ($2::text = '' OR status = $2)
  AND ($3::text = '' OR order_no ILIKE '%' || $3 || '%')
ORDER BY created_at DESC, order_no DESC
LIMIT $5 OFFSET $4
`

type ListPaymentOrdersParams struct {
	UserID       int64  `json:"user_id"`
	Status       string `json:"status"`
	Search       string `json:"search"`
	ResultOffset int32  `json:"result_offset"`
	ResultLimit  int32  `json:"result_limit"`
}

func (q *Queries) ListPaymentOrders(ctx context.Context, arg ListPaymentOrdersParams) ([]PaymentOrder, error) {
	rows, err := q.db.Query(ctx, listPaymentOrders,
		arg.UserID,
		arg.Status,
		arg.Search,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentOrder
	for rows.Next() {
		var i PaymentOrder
		if err := rows.Scan(
			&i.OrderNo,
			&i.UserID,
			&i.AmountCents,
			&i.Provider,
			&i.Channel,
			&i.Status,
			&i.PrepayID,
			&i.TransactionID,
			&i.PaidAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentOrderFailed = `-- name: MarkPaymentOrderFailed :execrows
UPDATE payment_orders
SET status = 'failed', updated_at = $2
WHERE order_no = $1 AND status = 'pending'
`

type MarkPaymentOrderFailedParams struct {
	OrderNo   string             `json:"order_no"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) MarkPaymentOrderFailed(ctx context.Context, arg MarkPaymentOrderFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPaymentOrderFailed, arg.OrderNo, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markPaymentOrderPaid = `-- name: MarkPaymentOrderPaid :one
UPDATE payment_orders
SET status = 'paid', transaction_id = $2, paid_at = $3, updated_at = $3
WHERE order_no = $1 AND status = 'pending'
RETURNING order_no, user_id, amount_cents, provider, channel, status, prepay_id, transaction_id, paid_at, cancelled_at, created_at, updated_at
`

type MarkPaymentOrderPaidParams struct {
	OrderNo       string             `json:"order_no"`
	TransactionID *string            `json:"transaction_id"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
}

func (q *Queries) MarkPaymentOrderPaid(ctx context.Context, arg MarkPaymentOrderPaidParams) (PaymentOrder, error) {
	row := q.db.QueryRow(ctx, markPaymentOrderPaid, arg.OrderNo, arg.TransactionID, arg.PaidAt)
	var i PaymentOrder
	err := row.Scan(
		&i.OrderNo,
		&i.UserID,
		&i.AmountCents,
		&i.Provider,
		&i.Channel,
		&i.Status,
		&i.PrepayID,
		&i.TransactionID,
		&i.PaidAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const savePaymentOrderPrepared = `-- name: SavePaymentOrderPrepared :one
UPDATE payment_orders
SET prepay_id = $2, updated_at = $3
WHERE order_no = $1 AND status = 'pending' AND (prepay_id IS NULL OR prepay_id = $2)
RETURNING order_no, user_id, amount_cents, provider, channel, status, prepay_id, transaction_id, paid_at, cancelled_at, created_at, updated_at
`

type SavePaymentOrderPreparedParams struct {
	OrderNo   string             `json:"order_no"`
	PrepayID  *string            `json:"prepay_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SavePaymentOrderPrepared(ctx context.Context, arg SavePaymentOrderPreparedParams) (PaymentOrder, error) {
	row := q.db.QueryRow(ctx, savePaymentOrderPrepared, arg.OrderNo, arg.PrepayID, arg.UpdatedAt)
	var i PaymentOrder
	err := row.Scan(
		&i.OrderNo,
		&i.UserID,
		&i.AmountCents,
		&i.Provider,
		&i.Channel,
		&i.Status,
		&i.PrepayID,
		&i.TransactionID,
		&i.PaidAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
