// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: match.sql

package matchsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAttendingRegistrationsForGroup = `-- name: CountAttendingRegistrationsForGroup :one
SELECT COALESCE(SUM(registration_count), 0)::bigint
FROM match_registrations
WHERE group_id = $1
  AND status = 'attending'
`

func (q *Queries) CountAttendingRegistrationsForGroup(ctx context.Context, groupID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAttendingRegistrationsForGroup, groupID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countMatchesForAdmin = `-- name: CountMatchesForAdmin :one
SELECT COUNT(*)
FROM matches m
JOIN teams host ON host.id = m.host_team_id
WHERE ($1::text IS NULL OR m.status = $1)
  AND (
      $2::text = ''
      OR m.name ILIKE '%' || $2 || '%'
      OR m.location ILIKE '%' || $2 || '%'
	      OR host.name ILIKE '%' || $2 || '%'
	  )
`

type CountMatchesForAdminParams struct {
	Status *string `json:"status"`
	Search string  `json:"search"`
}

func (q *Queries) CountMatchesForAdmin(ctx context.Context, arg CountMatchesForAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMatchesForAdmin, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMatchesForUser = `-- name: CountMatchesForUser :one
SELECT COUNT(*)
FROM matches m
JOIN teams host ON host.id = m.host_team_id
WHERE ($1::text IS NULL OR m.status = $1)
  AND (
      $2::text = ''
      OR m.name ILIKE '%' || $2 || '%'
      OR m.location ILIKE '%' || $2 || '%'
      OR host.name ILIKE '%' || $2 || '%'
  )
  AND (
      $3::text = 'all'
      OR (
          $3::text = 'mine'
          AND (
              EXISTS (
                  SELECT 1
                  FROM match_registration_groups registration_group
                  JOIN match_registrations registration ON registration.group_id = registration_group.id
                  WHERE registration_group.match_id = m.id
                    AND registration.user_id = $4
                    AND registration.status <> 'cancelled'
              )
              OR EXISTS (
                  SELECT 1
                  FROM team_members membership
                  WHERE membership.user_id = $4
                    AND membership.status = 'active'
                    AND (membership.team_id = m.host_team_id OR membership.team_id = m.away_team_id)
              )
          )
      )
      OR (
          $3::text = 'others'
          AND NOT EXISTS (
              SELECT 1
              FROM match_registration_groups registration_group
              JOIN match_registrations registration ON registration.group_id = registration_group.id
              WHERE registration_group.match_id = m.id
                AND registration.user_id = $4
                AND registration.status <> 'cancelled'
          )
          AND NOT EXISTS (
              SELECT 1
              FROM team_members membership
              WHERE membership.user_id = $4
                AND membership.status = 'active'
                AND (membership.team_id = m.host_team_id OR membership.team_id = m.away_team_id)
          )
      )
  )
  AND (
      $5::timestamp IS NULL
      OR m.start_time > $5::timestamp
  )
  AND (
      cardinality($6::text[]) = 0
      OR m.publication_mode = ANY($6::text[])
  )
  AND (
      $7::timestamp IS NULL
      OR (
          m.start_time >= $7::timestamp
          AND m.start_time < $7::timestamp + INTERVAL '1 day'
      )
  )
`

type CountMatchesForUserParams struct {
	Status           *string          `json:"status"`
	Search           string           `json:"search"`
	Scope            string           `json:"scope"`
	UserID           int64            `json:"user_id"`
	StartsAfter      pgtype.Timestamp `json:"starts_after"`
	PublicationModes []string         `json:"publication_modes"`
	DateStart        pgtype.Timestamp `json:"date_start"`
}

func (q *Queries) CountMatchesForUser(ctx context.Context, arg CountMatchesForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMatchesForUser,
		arg.Status,
		arg.Search,
		arg.Scope,
		arg.UserID,
		arg.StartsAfter,
		arg.PublicationModes,
		arg.DateStart,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (
    id,
    name,
    publication_mode,
    opponent_state,
    status,
    host_team_id,
    away_team_id,
    opponent_name,
    players_per_team,
    start_time,
    end_time,
    registration_start_at,
    registration_end_at,
    location,
    location_latitude,
    location_longitude,
    description,
    created_by_user_id,
    created_by_admin_id
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19
)
RETURNING id, name, publication_mode, opponent_state, status, host_team_id, away_team_id, opponent_name, players_per_team, start_time, end_time, location, location_latitude, location_longitude, description, created_by_user_id, created_at, updated_at, created_by_admin_id, registration_start_at, registration_end_at
`

type CreateMatchParams struct {
	ID                  pgtype.UUID      `json:"id"`
	Name                string           `json:"name"`
	PublicationMode     string           `json:"publication_mode"`
	OpponentState       string           `json:"opponent_state"`
	Status              string           `json:"status"`
	HostTeamID          int64            `json:"host_team_id"`
	AwayTeamID          *int64           `json:"away_team_id"`
	OpponentName        *string          `json:"opponent_name"`
	PlayersPerTeam      int32            `json:"players_per_team"`
	StartTime           pgtype.Timestamp `json:"start_time"`
	EndTime             pgtype.Timestamp `json:"end_time"`
	RegistrationStartAt pgtype.Timestamp `json:"registration_start_at"`
	RegistrationEndAt   pgtype.Timestamp `json:"registration_end_at"`
	Location            string           `json:"location"`
	LocationLatitude    *float64         `json:"location_latitude"`
	LocationLongitude   *float64         `json:"location_longitude"`
	Description         *string          `json:"description"`
	CreatedByUserID     *int64           `json:"created_by_user_id"`
	CreatedByAdminID    *int64           `json:"created_by_admin_id"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, createMatch,
		arg.ID,
		arg.Name,
		arg.PublicationMode,
		arg.OpponentState,
		arg.Status,
		arg.HostTeamID,
		arg.AwayTeamID,
		arg.OpponentName,
		arg.PlayersPerTeam,
		arg.StartTime,
		arg.EndTime,
		arg.RegistrationStartAt,
		arg.RegistrationEndAt,
		arg.Location,
		arg.LocationLatitude,
		arg.LocationLongitude,
		arg.Description,
		arg.CreatedByUserID,
		arg.CreatedByAdminID,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicationMode,
		&i.OpponentState,
		&i.Status,
		&i.HostTeamID,
		&i.AwayTeamID,
		&i.OpponentName,
		&i.PlayersPerTeam,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.LocationLatitude,
		&i.LocationLongitude,
		&i.Description,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByAdminID,
		&i.RegistrationStartAt,
		&i.RegistrationEndAt,
	)
	return i, err
}

const createRegistration = `-- name: CreateRegistration :exec
INSERT INTO match_registrations (
    id,
    group_id,
    user_id,
    status,
    registration_count,
    created_at,
    updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type CreateRegistrationParams struct {
	ID                pgtype.UUID      `json:"id"`
	GroupID           pgtype.UUID      `json:"group_id"`
	UserID            int64            `json:"user_id"`
	Status            string           `json:"status"`
	RegistrationCount int32            `json:"registration_count"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateRegistration(ctx context.Context, arg CreateRegistrationParams) error {
	_, err := q.db.Exec(ctx, createRegistration,
		arg.ID,
		arg.GroupID,
		arg.UserID,
		arg.Status,
		arg.RegistrationCount,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createRegistrationGroup = `-- name: CreateRegistrationGroup :one
INSERT INTO match_registration_groups (
    id,
    match_id,
    kind,
    team_id,
    min_players,
    max_players,
    status
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, match_id, kind, team_id, min_players, max_players, status, created_at, updated_at, cancelled_at
`

type CreateRegistrationGroupParams struct {
	ID         pgtype.UUID `json:"id"`
	MatchID    pgtype.UUID `json:"match_id"`
	Kind       string      `json:"kind"`
	TeamID     *int64      `json:"team_id"`
	MinPlayers *int32      `json:"min_players"`
	MaxPlayers *int32      `json:"max_players"`
	Status     string      `json:"status"`
}

func (q *Queries) CreateRegistrationGroup(ctx context.Context, arg CreateRegistrationGroupParams) (MatchRegistrationGroup, error) {
	row := q.db.QueryRow(ctx, createRegistrationGroup,
		arg.ID,
		arg.MatchID,
		arg.Kind,
		arg.TeamID,
		arg.MinPlayers,
		arg.MaxPlayers,
		arg.Status,
	)
	var i MatchRegistrationGroup
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.Kind,
		&i.TeamID,
		&i.MinPlayers,
		&i.MaxPlayers,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const createTeamApplication = `-- name: CreateTeamApplication :exec
INSERT INTO match_team_applications (
    id,
    match_id,
    applicant_team_id,
    introduction,
    status,
    created_by_user_id,
    selected_at,
    withdrawn_at,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateTeamApplicationParams struct {
	ID              pgtype.UUID      `json:"id"`
	MatchID         pgtype.UUID      `json:"match_id"`
	ApplicantTeamID int64            `json:"applicant_team_id"`
	Introduction    string           `json:"introduction"`
	Status          string           `json:"status"`
	CreatedByUserID int64            `json:"created_by_user_id"`
	SelectedAt      pgtype.Timestamp `json:"selected_at"`
	WithdrawnAt     pgtype.Timestamp `json:"withdrawn_at"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateTeamApplication(ctx context.Context, arg CreateTeamApplicationParams) error {
	_, err := q.db.Exec(ctx, createTeamApplication,
		arg.ID,
		arg.MatchID,
		arg.ApplicantTeamID,
		arg.Introduction,
		arg.Status,
		arg.CreatedByUserID,
		arg.SelectedAt,
		arg.WithdrawnAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteMatch = `-- name: DeleteMatch :execrows
DELETE FROM matches
WHERE id = $1
`

func (q *Queries) DeleteMatch(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMatch, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveGuestGroupForUpdate = `-- name: GetActiveGuestGroupForUpdate :one
SELECT id, match_id, kind, team_id, min_players, max_players, status, created_at, updated_at, cancelled_at
FROM match_registration_groups
WHERE match_id = $1
  AND kind = 'guest_team'
  AND status <> 'cancelled'
FOR UPDATE
`

func (q *Queries) GetActiveGuestGroupForUpdate(ctx context.Context, matchID pgtype.UUID) (MatchRegistrationGroup, error) {
	row := q.db.QueryRow(ctx, getActiveGuestGroupForUpdate, matchID)
	var i MatchRegistrationGroup
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.Kind,
		&i.TeamID,
		&i.MinPlayers,
		&i.MaxPlayers,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const getActiveUserRegistrationInMatchForUpdate = `-- name: GetActiveUserRegistrationInMatchForUpdate :one
SELECT registration.id, registration.group_id, registration.user_id, registration.status, registration.registration_count, registration.created_at, registration.updated_at, registration.cancelled_at
FROM match_registrations registration
JOIN match_registration_groups registration_group
  ON registration_group.id = registration.group_id
WHERE registration_group.match_id = $1
  AND registration_group.status <> 'cancelled'
  AND registration.user_id = $2
  AND registration.status <> 'cancelled'
ORDER BY registration.created_at, registration.id
LIMIT 1
FOR UPDATE OF registration
`

type GetActiveUserRegistrationInMatchForUpdateParams struct {
	MatchID pgtype.UUID `json:"match_id"`
	UserID  int64       `json:"user_id"`
}

func (q *Queries) GetActiveUserRegistrationInMatchForUpdate(ctx context.Context, arg GetActiveUserRegistrationInMatchForUpdateParams) (MatchRegistration, error) {
	row := q.db.QueryRow(ctx, getActiveUserRegistrationInMatchForUpdate, arg.MatchID, arg.UserID)
	var i MatchRegistration
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Status,
		&i.RegistrationCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const getMatchByID = `-- name: GetMatchByID :one
SELECT id, name, publication_mode, opponent_state, status, host_team_id, away_team_id, opponent_name, players_per_team, start_time, end_time, location, location_latitude, location_longitude, description, created_by_user_id, created_at, updated_at, created_by_admin_id, registration_start_at, registration_end_at
FROM matches
WHERE id = $1
`

func (q *Queries) GetMatchByID(ctx context.Context, id pgtype.UUID) (Match, error) {
	row := q.db.QueryRow(ctx, getMatchByID, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicationMode,
		&i.OpponentState,
		&i.Status,
		&i.HostTeamID,
		&i.AwayTeamID,
		&i.OpponentName,
		&i.PlayersPerTeam,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.LocationLatitude,
		&i.LocationLongitude,
		&i.Description,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByAdminID,
		&i.RegistrationStartAt,
		&i.RegistrationEndAt,
	)
	return i, err
}

const getMatchByIDForUpdate = `-- name: GetMatchByIDForUpdate :one
SELECT id, name, publication_mode, opponent_state, status, host_team_id, away_team_id, opponent_name, players_per_team, start_time, end_time, location, location_latitude, location_longitude, description, created_by_user_id, created_at, updated_at, created_by_admin_id, registration_start_at, registration_end_at
FROM matches
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetMatchByIDForUpdate(ctx context.Context, id pgtype.UUID) (Match, error) {
	row := q.db.QueryRow(ctx, getMatchByIDForUpdate, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicationMode,
		&i.OpponentState,
		&i.Status,
		&i.HostTeamID,
		&i.AwayTeamID,
		&i.OpponentName,
		&i.PlayersPerTeam,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.LocationLatitude,
		&i.LocationLongitude,
		&i.Description,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByAdminID,
		&i.RegistrationStartAt,
		&i.RegistrationEndAt,
	)
	return i, err
}

const getMatchForAdmin = `-- name: GetMatchForAdmin :one
SELECT m.id, m.name, m.publication_mode, m.opponent_state, m.status, m.host_team_id, m.away_team_id, m.opponent_name, m.players_per_team, m.start_time, m.end_time, m.location, m.location_latitude, m.location_longitude, m.description, m.created_by_user_id, m.created_at, m.updated_at, m.created_by_admin_id, m.registration_start_at, m.registration_end_at,
       host.name AS host_team_name,
       away.name AS away_team_name
FROM matches m
JOIN teams host ON host.id = m.host_team_id
LEFT JOIN teams away ON away.id = m.away_team_id
WHERE m.id = $1
`

type GetMatchForAdminRow struct {
	ID                  pgtype.UUID      `json:"id"`
	Name                string           `json:"name"`
	PublicationMode     string           `json:"publication_mode"`
	OpponentState       string           `json:"opponent_state"`
	Status              string           `json:"status"`
	HostTeamID          int64            `json:"host_team_id"`
	AwayTeamID          *int64           `json:"away_team_id"`
	OpponentName        *string          `json:"opponent_name"`
	PlayersPerTeam      int32            `json:"players_per_team"`
	StartTime           pgtype.Timestamp `json:"start_time"`
	EndTime             pgtype.Timestamp `json:"end_time"`
	Location            string           `json:"location"`
	LocationLatitude    *float64         `json:"location_latitude"`
	LocationLongitude   *float64         `json:"location_longitude"`
	Description         *string          `json:"description"`
	CreatedByUserID     *int64           `json:"created_by_user_id"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	CreatedByAdminID    *int64           `json:"created_by_admin_id"`
	RegistrationStartAt pgtype.Timestamp `json:"registration_start_at"`
	RegistrationEndAt   pgtype.Timestamp `json:"registration_end_at"`
	HostTeamName        string           `json:"host_team_name"`
	AwayTeamName        *string          `json:"away_team_name"`
}

func (q *Queries) GetMatchForAdmin(ctx context.Context, id pgtype.UUID) (GetMatchForAdminRow, error) {
	row := q.db.QueryRow(ctx, getMatchForAdmin, id)
	var i GetMatchForAdminRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicationMode,
		&i.OpponentState,
		&i.Status,
		&i.HostTeamID,
		&i.AwayTeamID,
		&i.OpponentName,
		&i.PlayersPerTeam,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.LocationLatitude,
		&i.LocationLongitude,
		&i.Description,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByAdminID,
		&i.RegistrationStartAt,
		&i.RegistrationEndAt,
		&i.HostTeamName,
		&i.AwayTeamName,
	)
	return i, err
}

const getRegistrationGroupForUpdate = `-- name: GetRegistrationGroupForUpdate :one
SELECT id, match_id, kind, team_id, min_players, max_players, status, created_at, updated_at, cancelled_at
FROM match_registration_groups
WHERE match_id = $1
  AND id = $2
FOR UPDATE
`

type GetRegistrationGroupForUpdateParams struct {
	MatchID pgtype.UUID `json:"match_id"`
	GroupID pgtype.UUID `json:"group_id"`
}

func (q *Queries) GetRegistrationGroupForUpdate(ctx context.Context, arg GetRegistrationGroupForUpdateParams) (MatchRegistrationGroup, error) {
	row := q.db.QueryRow(ctx, getRegistrationGroupForUpdate, arg.MatchID, arg.GroupID)
	var i MatchRegistrationGroup
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.Kind,
		&i.TeamID,
		&i.MinPlayers,
		&i.MaxPlayers,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const getTeamApplicationByIDForUpdate = `-- name: GetTeamApplicationByIDForUpdate :one
SELECT id, match_id, applicant_team_id, introduction, status, created_by_user_id, selected_at, withdrawn_at, created_at, updated_at
FROM match_team_applications
WHERE match_id = $1
  AND id = $2
FOR UPDATE
`

type GetTeamApplicationByIDForUpdateParams struct {
	MatchID pgtype.UUID `json:"match_id"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) GetTeamApplicationByIDForUpdate(ctx context.Context, arg GetTeamApplicationByIDForUpdateParams) (MatchTeamApplication, error) {
	row := q.db.QueryRow(ctx, getTeamApplicationByIDForUpdate, arg.MatchID, arg.ID)
	var i MatchTeamApplication
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.ApplicantTeamID,
		&i.Introduction,
		&i.Status,
		&i.CreatedByUserID,
		&i.SelectedAt,
		&i.WithdrawnAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRegistrationForUpdate = `-- name: GetUserRegistrationForUpdate :one
SELECT id, group_id, user_id, status, registration_count, created_at, updated_at, cancelled_at
FROM match_registrations
WHERE group_id = $1
  AND user_id = $2
FOR UPDATE
`

type GetUserRegistrationForUpdateParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  int64       `json:"user_id"`
}

func (q *Queries) GetUserRegistrationForUpdate(ctx context.Context, arg GetUserRegistrationForUpdateParams) (MatchRegistration, error) {
	row := q.db.QueryRow(ctx, getUserRegistrationForUpdate, arg.GroupID, arg.UserID)
	var i MatchRegistration
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Status,
		&i.RegistrationCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const isActiveTeamMember = `-- name: IsActiveTeamMember :one
SELECT EXISTS (
    SELECT 1
    FROM team_members
    WHERE team_id = $1
      AND user_id = $2
      AND status = 'active'
)
`

type IsActiveTeamMemberParams struct {
	TeamID int64 `json:"team_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) IsActiveTeamMember(ctx context.Context, arg IsActiveTeamMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isActiveTeamMember, arg.TeamID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listGroupRegistrations = `-- name: ListGroupRegistrations :many
SELECT r.user_id,
       u.nickname,
       u.avatar_url,
       u.real_name,
       r.status AS registration_status
FROM match_registrations r
JOIN users u ON u.id = r.user_id
WHERE r.group_id = $1
ORDER BY
    CASE r.status
        WHEN 'attending' THEN 0
        WHEN 'unknown' THEN 1
        WHEN 'leave' THEN 3
        WHEN 'absent' THEN 4
        ELSE 5
    END,
    r.created_at,
    r.user_id
`

type ListGroupRegistrationsRow struct {
	UserID             int64   `json:"user_id"`
	Nickname           string  `json:"nickname"`
	AvatarUrl          *string `json:"avatar_url"`
	RealName           *string `json:"real_name"`
	RegistrationStatus string  `json:"registration_status"`
}

// 报名组的全部报名记录（含用户资料）；个人组花名册与用户端详情 participants 共用。
func (q *Queries) ListGroupRegistrations(ctx context.Context, groupID pgtype.UUID) ([]ListGroupRegistrationsRow, error) {
	rows, err := q.db.Query(ctx, listGroupRegistrations, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupRegistrationsRow
	for rows.Next() {
		var i ListGroupRegistrationsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Nickname,
			&i.AvatarUrl,
			&i.RealName,
			&i.RegistrationStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeActionGroupParticipants = `-- name: ListHomeActionGroupParticipants :many
SELECT r.group_id,
       r.user_id,
       u.nickname,
       u.avatar_url,
       r.status
FROM match_registrations r
JOIN users u ON u.id = r.user_id
WHERE r.group_id = ANY($1::uuid[])
  AND r.status = 'attending'
ORDER BY r.group_id, r.created_at, r.user_id
`

type ListHomeActionGroupParticipantsRow struct {
	GroupID   pgtype.UUID `json:"group_id"`
	UserID    int64       `json:"user_id"`
	Nickname  string      `json:"nickname"`
	AvatarUrl *string     `json:"avatar_url"`
	Status    string      `json:"status"`
}

// 首页比赛卡片的报名人头像列表：一次性按 group 批量取全部 attending 报名者，
// 按报名先后（created_at, user_id）排序，避免 N+1 查询。
func (q *Queries) ListHomeActionGroupParticipants(ctx context.Context, groupIds []pgtype.UUID) ([]ListHomeActionGroupParticipantsRow, error) {
	rows, err := q.db.Query(ctx, listHomeActionGroupParticipants, groupIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHomeActionGroupParticipantsRow
	for rows.Next() {
		var i ListHomeActionGroupParticipantsRow
		if err := rows.Scan(
			&i.GroupID,
			&i.UserID,
			&i.Nickname,
			&i.AvatarUrl,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeActionMatchesForUser = `-- name: ListHomeActionMatchesForUser :many
SELECT m.id, m.name, m.publication_mode, m.opponent_state, m.status, m.host_team_id, m.away_team_id, m.opponent_name, m.players_per_team, m.start_time, m.end_time, m.location, m.location_latitude, m.location_longitude, m.description, m.created_by_user_id, m.created_at, m.updated_at, m.created_by_admin_id, m.registration_start_at, m.registration_end_at,
       host.name AS host_team_name,
       away.name AS away_team_name,
       related_group.id AS group_id,
       related_group.kind AS group_kind,
       related_group.team_id AS group_team_id,
       related_group.min_players AS group_min_players,
       related_group.max_players AS group_max_players,
       related_group.status AS group_status,
       related_group.created_at AS group_created_at,
       related_group.updated_at AS group_updated_at,
       related_group.cancelled_at AS group_cancelled_at,
       COALESCE((
           SELECT SUM(active.registration_count)
           FROM match_registrations active
           WHERE active.group_id = related_group.id
             AND active.status = 'attending'
       ), 0)::bigint AS attending_count,
       mine.id AS my_registration_id,
       mine.status AS my_registration_status,
       mine.registration_count AS my_registration_count,
       mine.created_at AS my_registration_created_at,
       mine.updated_at AS my_registration_updated_at,
       mine.cancelled_at AS my_registration_cancelled_at
FROM matches m
JOIN teams host ON host.id = m.host_team_id
LEFT JOIN teams away ON away.id = m.away_team_id
JOIN LATERAL (
    SELECT g.id, g.match_id, g.kind, g.team_id, g.min_players, g.max_players, g.status, g.created_at, g.updated_at, g.cancelled_at
    FROM match_registration_groups g
    LEFT JOIN match_registrations own
      ON own.group_id = g.id
     AND own.user_id = $1
    WHERE g.match_id = m.id
      AND g.status <> 'cancelled'
      AND (
          own.id IS NOT NULL
          OR (
              g.team_id IS NOT NULL
              AND EXISTS (
                  SELECT 1
                  FROM team_members tm
                  WHERE tm.team_id = g.team_id
                    AND tm.user_id = $1
                    AND tm.status = 'active'
              )
          )
      )
    ORDER BY
        CASE WHEN own.id IS NOT NULL THEN 0 ELSE 1 END,
        CASE g.kind WHEN 'host_team' THEN 0 WHEN 'guest_team' THEN 1 ELSE 2 END,
        g.created_at,
        g.id
    LIMIT 1
) related_group ON TRUE
LEFT JOIN match_registrations mine
  ON mine.group_id = related_group.id
 AND mine.user_id = $1
WHERE m.status IN ('registering', 'ongoing')
  AND m.end_time > NOW()
ORDER BY
    CASE m.status WHEN 'ongoing' THEN 0 ELSE 1 END,
    m.start_time,
    m.id
LIMIT $2
`

type ListHomeActionMatchesForUserParams struct {
	UserID     int64 `json:"user_id"`
	LimitCount int32 `json:"limit_count"`
}

type ListHomeActionMatchesForUserRow struct {
	ID                        pgtype.UUID      `json:"id"`
	Name                      string           `json:"name"`
	PublicationMode           string           `json:"publication_mode"`
	OpponentState             string           `json:"opponent_state"`
	Status                    string           `json:"status"`
	HostTeamID                int64            `json:"host_team_id"`
	AwayTeamID                *int64           `json:"away_team_id"`
	OpponentName              *string          `json:"opponent_name"`
	PlayersPerTeam            int32            `json:"players_per_team"`
	StartTime                 pgtype.Timestamp `json:"start_time"`
	EndTime                   pgtype.Timestamp `json:"end_time"`
	Location                  string           `json:"location"`
	LocationLatitude          *float64         `json:"location_latitude"`
	LocationLongitude         *float64         `json:"location_longitude"`
	Description               *string          `json:"description"`
	CreatedByUserID           *int64           `json:"created_by_user_id"`
	CreatedAt                 pgtype.Timestamp `json:"created_at"`
	UpdatedAt                 pgtype.Timestamp `json:"updated_at"`
	CreatedByAdminID          *int64           `json:"created_by_admin_id"`
	RegistrationStartAt       pgtype.Timestamp `json:"registration_start_at"`
	RegistrationEndAt         pgtype.Timestamp `json:"registration_end_at"`
	HostTeamName              string           `json:"host_team_name"`
	AwayTeamName              *string          `json:"away_team_name"`
	GroupID                   pgtype.UUID      `json:"group_id"`
	GroupKind                 string           `json:"group_kind"`
	GroupTeamID               *int64           `json:"group_team_id"`
	GroupMinPlayers           *int32           `json:"group_min_players"`
	GroupMaxPlayers           *int32           `json:"group_max_players"`
	GroupStatus               string           `json:"group_status"`
	GroupCreatedAt            pgtype.Timestamp `json:"group_created_at"`
	GroupUpdatedAt            pgtype.Timestamp `json:"group_updated_at"`
	GroupCancelledAt          pgtype.Timestamp `json:"group_cancelled_at"`
	AttendingCount            int64            `json:"attending_count"`
	MyRegistrationID          pgtype.UUID      `json:"my_registration_id"`
	MyRegistrationStatus      *string          `json:"my_registration_status"`
	MyRegistrationCount       *int32           `json:"my_registration_count"`
	MyRegistrationCreatedAt   pgtype.Timestamp `json:"my_registration_created_at"`
	MyRegistrationUpdatedAt   pgtype.Timestamp `json:"my_registration_updated_at"`
	MyRegistrationCancelledAt pgtype.Timestamp `json:"my_registration_cancelled_at"`
}

func (q *Queries) ListHomeActionMatchesForUser(ctx context.Context, arg ListHomeActionMatchesForUserParams) ([]ListHomeActionMatchesForUserRow, error) {
	rows, err := q.db.Query(ctx, listHomeActionMatchesForUser, arg.UserID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHomeActionMatchesForUserRow
	for rows.Next() {
		var i ListHomeActionMatchesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PublicationMode,
			&i.OpponentState,
			&i.Status,
			&i.HostTeamID,
			&i.AwayTeamID,
			&i.OpponentName,
			&i.PlayersPerTeam,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
			&i.LocationLatitude,
			&i.LocationLongitude,
			&i.Description,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByAdminID,
			&i.RegistrationStartAt,
			&i.RegistrationEndAt,
			&i.HostTeamName,
			&i.AwayTeamName,
			&i.GroupID,
			&i.GroupKind,
			&i.GroupTeamID,
			&i.GroupMinPlayers,
			&i.GroupMaxPlayers,
			&i.GroupStatus,
			&i.GroupCreatedAt,
			&i.GroupUpdatedAt,
			&i.GroupCancelledAt,
			&i.AttendingCount,
			&i.MyRegistrationID,
			&i.MyRegistrationStatus,
			&i.MyRegistrationCount,
			&i.MyRegistrationCreatedAt,
			&i.MyRegistrationUpdatedAt,
			&i.MyRegistrationCancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeEndedMatchParticipants = `-- name: ListHomeEndedMatchParticipants :many
SELECT g.match_id,
       r.user_id,
       u.nickname,
       u.avatar_url,
       r.status
FROM match_registration_groups g
JOIN match_registrations r ON r.group_id = g.id
JOIN users u ON u.id = r.user_id
WHERE g.match_id = ANY($1::uuid[])
  AND g.status <> 'cancelled'
  AND r.status = 'attending'
ORDER BY g.match_id, r.created_at, r.user_id
`

type ListHomeEndedMatchParticipantsRow struct {
	MatchID   pgtype.UUID `json:"match_id"`
	UserID    int64       `json:"user_id"`
	Nickname  string      `json:"nickname"`
	AvatarUrl *string     `json:"avatar_url"`
	Status    string      `json:"status"`
}

// 首页已结束比赛卡片的报名人头像列表：一次性按 match 批量取全部 attending 报名者，
// 合并该比赛全部报名组后按报名先后（created_at, user_id）排序，避免 N+1 查询。
func (q *Queries) ListHomeEndedMatchParticipants(ctx context.Context, matchIds []pgtype.UUID) ([]ListHomeEndedMatchParticipantsRow, error) {
	rows, err := q.db.Query(ctx, listHomeEndedMatchParticipants, matchIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHomeEndedMatchParticipantsRow
	for rows.Next() {
		var i ListHomeEndedMatchParticipantsRow
		if err := rows.Scan(
			&i.MatchID,
			&i.UserID,
			&i.Nickname,
			&i.AvatarUrl,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeEndedMatchesForUser = `-- name: ListHomeEndedMatchesForUser :many
SELECT m.id, m.name, m.publication_mode, m.opponent_state, m.status, m.host_team_id, m.away_team_id, m.opponent_name, m.players_per_team, m.start_time, m.end_time, m.location, m.location_latitude, m.location_longitude, m.description, m.created_by_user_id, m.created_at, m.updated_at, m.created_by_admin_id, m.registration_start_at, m.registration_end_at,
       host.name AS host_team_name,
       away.name AS away_team_name
FROM matches m
JOIN teams host ON host.id = m.host_team_id
LEFT JOIN teams away ON away.id = m.away_team_id
WHERE m.status <> 'cancelled'
  AND (m.status = 'ended' OR m.end_time <= NOW())
  AND (
      EXISTS (
          SELECT 1
          FROM team_members tm
          WHERE tm.user_id = $1
            AND tm.status = 'active'
            AND (tm.team_id = m.host_team_id OR tm.team_id = m.away_team_id)
      )
      OR EXISTS (
          SELECT 1
          FROM match_registration_groups g
          JOIN match_registrations registration ON registration.group_id = g.id
          WHERE g.match_id = m.id
            AND registration.user_id = $1
      )
  )
ORDER BY m.end_time DESC, m.id
LIMIT $2
`

type ListHomeEndedMatchesForUserParams struct {
	UserID     int64 `json:"user_id"`
	LimitCount int32 `json:"limit_count"`
}

type ListHomeEndedMatchesForUserRow struct {
	ID                  pgtype.UUID      `json:"id"`
	Name                string           `json:"name"`
	PublicationMode     string           `json:"publication_mode"`
	OpponentState       string           `json:"opponent_state"`
	Status              string           `json:"status"`
	HostTeamID          int64            `json:"host_team_id"`
	AwayTeamID          *int64           `json:"away_team_id"`
	OpponentName        *string          `json:"opponent_name"`
	PlayersPerTeam      int32            `json:"players_per_team"`
	StartTime           pgtype.Timestamp `json:"start_time"`
	EndTime             pgtype.Timestamp `json:"end_time"`
	Location            string           `json:"location"`
	LocationLatitude    *float64         `json:"location_latitude"`
	LocationLongitude   *float64         `json:"location_longitude"`
	Description         *string          `json:"description"`
	CreatedByUserID     *int64           `json:"created_by_user_id"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	CreatedByAdminID    *int64           `json:"created_by_admin_id"`
	RegistrationStartAt pgtype.Timestamp `json:"registration_start_at"`
	RegistrationEndAt   pgtype.Timestamp `json:"registration_end_at"`
	HostTeamName        string           `json:"host_team_name"`
	AwayTeamName        *string          `json:"away_team_name"`
}

func (q *Queries) ListHomeEndedMatchesForUser(ctx context.Context, arg ListHomeEndedMatchesForUserParams) ([]ListHomeEndedMatchesForUserRow, error) {
	rows, err := q.db.Query(ctx, listHomeEndedMatchesForUser, arg.UserID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHomeEndedMatchesForUserRow
	for rows.Next() {
		var i ListHomeEndedMatchesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PublicationMode,
			&i.OpponentState,
			&i.Status,
			&i.HostTeamID,
			&i.AwayTeamID,
			&i.OpponentName,
			&i.PlayersPerTeam,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
			&i.LocationLatitude,
			&i.LocationLongitude,
			&i.Description,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByAdminID,
			&i.RegistrationStartAt,
			&i.RegistrationEndAt,
			&i.HostTeamName,
			&i.AwayTeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesForAdmin = `-- name: ListMatchesForAdmin :many
SELECT m.id, m.name, m.publication_mode, m.opponent_state, m.status, m.host_team_id, m.away_team_id, m.opponent_name, m.players_per_team, m.start_time, m.end_time, m.location, m.location_latitude, m.location_longitude, m.description, m.created_by_user_id, m.created_at, m.updated_at, m.created_by_admin_id, m.registration_start_at, m.registration_end_at,
       host.name AS host_team_name,
       away.name AS away_team_name
FROM matches m
JOIN teams host ON host.id = m.host_team_id
LEFT JOIN teams away ON away.id = m.away_team_id
WHERE ($1::text IS NULL OR m.status = $1)
  AND (
      $2::text = ''
      OR m.name ILIKE '%' || $2 || '%'
      OR m.location ILIKE '%' || $2 || '%'
      OR host.name ILIKE '%' || $2 || '%'
  )
ORDER BY m.start_time DESC, m.id
LIMIT $4 OFFSET $3
`

type ListMatchesForAdminParams struct {
	Status      *string `json:"status"`
	Search      string  `json:"search"`
	OffsetCount int32   `json:"offset_count"`
	LimitCount  int32   `json:"limit_count"`
}

type ListMatchesForAdminRow struct {
	ID                  pgtype.UUID      `json:"id"`
	Name                string           `json:"name"`
	PublicationMode     string           `json:"publication_mode"`
	OpponentState       string           `json:"opponent_state"`
	Status              string           `json:"status"`
	HostTeamID          int64            `json:"host_team_id"`
	AwayTeamID          *int64           `json:"away_team_id"`
	OpponentName        *string          `json:"opponent_name"`
	PlayersPerTeam      int32            `json:"players_per_team"`
	StartTime           pgtype.Timestamp `json:"start_time"`
	EndTime             pgtype.Timestamp `json:"end_time"`
	Location            string           `json:"location"`
	LocationLatitude    *float64         `json:"location_latitude"`
	LocationLongitude   *float64         `json:"location_longitude"`
	Description         *string          `json:"description"`
	CreatedByUserID     *int64           `json:"created_by_user_id"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	CreatedByAdminID    *int64           `json:"created_by_admin_id"`
	RegistrationStartAt pgtype.Timestamp `json:"registration_start_at"`
	RegistrationEndAt   pgtype.Timestamp `json:"registration_end_at"`
	HostTeamName        string           `json:"host_team_name"`
	AwayTeamName        *string          `json:"away_team_name"`
}

func (q *Queries) ListMatchesForAdmin(ctx context.Context, arg ListMatchesForAdminParams) ([]ListMatchesForAdminRow, error) {
	rows, err := q.db.Query(ctx, listMatchesForAdmin,
		arg.Status,
		arg.Search,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchesForAdminRow
	for rows.Next() {
		var i ListMatchesForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PublicationMode,
			&i.OpponentState,
			&i.Status,
			&i.HostTeamID,
			&i.AwayTeamID,
			&i.OpponentName,
			&i.PlayersPerTeam,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
			&i.LocationLatitude,
			&i.LocationLongitude,
			&i.Description,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByAdminID,
			&i.RegistrationStartAt,
			&i.RegistrationEndAt,
			&i.HostTeamName,
			&i.AwayTeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesForUser = `-- name: ListMatchesForUser :many
SELECT m.id, m.name, m.publication_mode, m.opponent_state, m.status, m.host_team_id, m.away_team_id, m.opponent_name, m.players_per_team, m.start_time, m.end_time, m.location, m.location_latitude, m.location_longitude, m.description, m.created_by_user_id, m.created_at, m.updated_at, m.created_by_admin_id, m.registration_start_at, m.registration_end_at,
       host.name AS host_team_name,
       away.name AS away_team_name
FROM matches m
JOIN teams host ON host.id = m.host_team_id
LEFT JOIN teams away ON away.id = m.away_team_id
WHERE ($1::text IS NULL OR m.status = $1)
  AND (
      $2::text = ''
      OR m.name ILIKE '%' || $2 || '%'
      OR m.location ILIKE '%' || $2 || '%'
      OR host.name ILIKE '%' || $2 || '%'
  )
  AND (
      $3::text = 'all'
      OR (
          $3::text = 'mine'
          AND (
              EXISTS (
                  SELECT 1
                  FROM match_registration_groups registration_group
                  JOIN match_registrations registration ON registration.group_id = registration_group.id
                  WHERE registration_group.match_id = m.id
                    AND registration.user_id = $4
                    AND registration.status <> 'cancelled'
              )
              OR EXISTS (
                  SELECT 1
                  FROM team_members membership
                  WHERE membership.user_id = $4
                    AND membership.status = 'active'
                    AND (membership.team_id = m.host_team_id OR membership.team_id = m.away_team_id)
              )
          )
      )
      OR (
          $3::text = 'others'
          AND NOT EXISTS (
              SELECT 1
              FROM match_registration_groups registration_group
              JOIN match_registrations registration ON registration.group_id = registration_group.id
              WHERE registration_group.match_id = m.id
                AND registration.user_id = $4
                AND registration.status <> 'cancelled'
          )
          AND NOT EXISTS (
              SELECT 1
              FROM team_members membership
              WHERE membership.user_id = $4
                AND membership.status = 'active'
                AND (membership.team_id = m.host_team_id OR membership.team_id = m.away_team_id)
          )
      )
  )
  AND (
      $5::timestamp IS NULL
      OR m.start_time > $5::timestamp
  )
  AND (
      cardinality($6::text[]) = 0
      OR m.publication_mode = ANY($6::text[])
  )
  AND (
      $7::timestamp IS NULL
      OR (
          m.start_time >= $7::timestamp
          AND m.start_time < $7::timestamp + INTERVAL '1 day'
      )
  )
ORDER BY m.start_time DESC, m.id
LIMIT $9 OFFSET $8
`

type ListMatchesForUserParams struct {
	Status           *string          `json:"status"`
	Search           string           `json:"search"`
	Scope            string           `json:"scope"`
	UserID           int64            `json:"user_id"`
	StartsAfter      pgtype.Timestamp `json:"starts_after"`
	PublicationModes []string         `json:"publication_modes"`
	DateStart        pgtype.Timestamp `json:"date_start"`
	OffsetCount      int32            `json:"offset_count"`
	LimitCount       int32            `json:"limit_count"`
}

type ListMatchesForUserRow struct {
	ID                  pgtype.UUID      `json:"id"`
	Name                string           `json:"name"`
	PublicationMode     string           `json:"publication_mode"`
	OpponentState       string           `json:"opponent_state"`
	Status              string           `json:"status"`
	HostTeamID          int64            `json:"host_team_id"`
	AwayTeamID          *int64           `json:"away_team_id"`
	OpponentName        *string          `json:"opponent_name"`
	PlayersPerTeam      int32            `json:"players_per_team"`
	StartTime           pgtype.Timestamp `json:"start_time"`
	EndTime             pgtype.Timestamp `json:"end_time"`
	Location            string           `json:"location"`
	LocationLatitude    *float64         `json:"location_latitude"`
	LocationLongitude   *float64         `json:"location_longitude"`
	Description         *string          `json:"description"`
	CreatedByUserID     *int64           `json:"created_by_user_id"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	CreatedByAdminID    *int64           `json:"created_by_admin_id"`
	RegistrationStartAt pgtype.Timestamp `json:"registration_start_at"`
	RegistrationEndAt   pgtype.Timestamp `json:"registration_end_at"`
	HostTeamName        string           `json:"host_team_name"`
	AwayTeamName        *string          `json:"away_team_name"`
}

func (q *Queries) ListMatchesForUser(ctx context.Context, arg ListMatchesForUserParams) ([]ListMatchesForUserRow, error) {
	rows, err := q.db.Query(ctx, listMatchesForUser,
		arg.Status,
		arg.Search,
		arg.Scope,
		arg.UserID,
		arg.StartsAfter,
		arg.PublicationModes,
		arg.DateStart,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchesForUserRow
	for rows.Next() {
		var i ListMatchesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PublicationMode,
			&i.OpponentState,
			&i.Status,
			&i.HostTeamID,
			&i.AwayTeamID,
			&i.OpponentName,
			&i.PlayersPerTeam,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
			&i.LocationLatitude,
			&i.LocationLongitude,
			&i.Description,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByAdminID,
			&i.RegistrationStartAt,
			&i.RegistrationEndAt,
			&i.HostTeamName,
			&i.AwayTeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingTeamApplicationsForUpdate = `-- name: ListPendingTeamApplicationsForUpdate :many
SELECT id, match_id, applicant_team_id, introduction, status, created_by_user_id, selected_at, withdrawn_at, created_at, updated_at
FROM match_team_applications
WHERE match_id = $1
  AND status = 'pending'
ORDER BY created_at, id
FOR UPDATE
`

func (q *Queries) ListPendingTeamApplicationsForUpdate(ctx context.Context, matchID pgtype.UUID) ([]MatchTeamApplication, error) {
	rows, err := q.db.Query(ctx, listPendingTeamApplicationsForUpdate, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MatchTeamApplication
	for rows.Next() {
		var i MatchTeamApplication
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.ApplicantTeamID,
			&i.Introduction,
			&i.Status,
			&i.CreatedByUserID,
			&i.SelectedAt,
			&i.WithdrawnAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistrationGroupStatesForUser = `-- name: ListRegistrationGroupStatesForUser :many
SELECT g.id, g.match_id, g.kind, g.team_id, g.min_players, g.max_players, g.status, g.created_at, g.updated_at, g.cancelled_at,
       COALESCE((
           SELECT SUM(active.registration_count)
           FROM match_registrations active
           WHERE active.group_id = g.id
             AND active.status = 'attending'
       ), 0)::bigint AS attending_count,
       mine.id AS my_registration_id,
       mine.status AS my_registration_status,
       mine.registration_count AS my_registration_count,
       mine.created_at AS my_registration_created_at,
       mine.updated_at AS my_registration_updated_at,
       mine.cancelled_at AS my_registration_cancelled_at
FROM match_registration_groups g
LEFT JOIN match_registrations mine
    ON mine.group_id = g.id
   AND mine.user_id = $1
WHERE g.match_id = $2
ORDER BY g.created_at, g.id
`

type ListRegistrationGroupStatesForUserParams struct {
	UserID  int64       `json:"user_id"`
	MatchID pgtype.UUID `json:"match_id"`
}

type ListRegistrationGroupStatesForUserRow struct {
	ID                        pgtype.UUID      `json:"id"`
	MatchID                   pgtype.UUID      `json:"match_id"`
	Kind                      string           `json:"kind"`
	TeamID                    *int64           `json:"team_id"`
	MinPlayers                *int32           `json:"min_players"`
	MaxPlayers                *int32           `json:"max_players"`
	Status                    string           `json:"status"`
	CreatedAt                 pgtype.Timestamp `json:"created_at"`
	UpdatedAt                 pgtype.Timestamp `json:"updated_at"`
	CancelledAt               pgtype.Timestamp `json:"cancelled_at"`
	AttendingCount            int64            `json:"attending_count"`
	MyRegistrationID          pgtype.UUID      `json:"my_registration_id"`
	MyRegistrationStatus      *string          `json:"my_registration_status"`
	MyRegistrationCount       *int32           `json:"my_registration_count"`
	MyRegistrationCreatedAt   pgtype.Timestamp `json:"my_registration_created_at"`
	MyRegistrationUpdatedAt   pgtype.Timestamp `json:"my_registration_updated_at"`
	MyRegistrationCancelledAt pgtype.Timestamp `json:"my_registration_cancelled_at"`
}

func (q *Queries) ListRegistrationGroupStatesForUser(ctx context.Context, arg ListRegistrationGroupStatesForUserParams) ([]ListRegistrationGroupStatesForUserRow, error) {
	rows, err := q.db.Query(ctx, listRegistrationGroupStatesForUser, arg.UserID, arg.MatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRegistrationGroupStatesForUserRow
	for rows.Next() {
		var i ListRegistrationGroupStatesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.Kind,
			&i.TeamID,
			&i.MinPlayers,
			&i.MaxPlayers,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CancelledAt,
			&i.AttendingCount,
			&i.MyRegistrationID,
			&i.MyRegistrationStatus,
			&i.MyRegistrationCount,
			&i.MyRegistrationCreatedAt,
			&i.MyRegistrationUpdatedAt,
			&i.MyRegistrationCancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistrationGroupsByMatchID = `-- name: ListRegistrationGroupsByMatchID :many
SELECT id, match_id, kind, team_id, min_players, max_players, status, created_at, updated_at, cancelled_at
FROM match_registration_groups
WHERE match_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListRegistrationGroupsByMatchID(ctx context.Context, matchID pgtype.UUID) ([]MatchRegistrationGroup, error) {
	rows, err := q.db.Query(ctx, listRegistrationGroupsByMatchID, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MatchRegistrationGroup
	for rows.Next() {
		var i MatchRegistrationGroup
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.Kind,
			&i.TeamID,
			&i.MinPlayers,
			&i.MaxPlayers,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistrationSummariesForMatches = `-- name: ListRegistrationSummariesForMatches :many
SELECT g.match_id,
       g.id AS group_id,
       g.kind,
       g.team_id,
       g.min_players,
       g.max_players,
       COALESCE(SUM(r.registration_count) FILTER (WHERE r.status = 'attending'), 0)::bigint AS attending_count
FROM match_registration_groups g
LEFT JOIN match_registrations r ON r.group_id = g.id
WHERE g.match_id = ANY($1::uuid[])
  AND g.status <> 'cancelled'
GROUP BY g.match_id, g.id, g.kind, g.team_id, g.min_players, g.max_players
ORDER BY g.match_id, g.id
`

type ListRegistrationSummariesForMatchesRow struct {
	MatchID        pgtype.UUID `json:"match_id"`
	GroupID        pgtype.UUID `json:"group_id"`
	Kind           string      `json:"kind"`
	TeamID         *int64      `json:"team_id"`
	MinPlayers     *int32      `json:"min_players"`
	MaxPlayers     *int32      `json:"max_players"`
	AttendingCount int64       `json:"attending_count"`
}

func (q *Queries) ListRegistrationSummariesForMatches(ctx context.Context, matchIds []pgtype.UUID) ([]ListRegistrationSummariesForMatchesRow, error) {
	rows, err := q.db.Query(ctx, listRegistrationSummariesForMatches, matchIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRegistrationSummariesForMatchesRow
	for rows.Next() {
		var i ListRegistrationSummariesForMatchesRow
		if err := rows.Scan(
			&i.MatchID,
			&i.GroupID,
			&i.Kind,
			&i.TeamID,
			&i.MinPlayers,
			&i.MaxPlayers,
			&i.AttendingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamApplications = `-- name: ListTeamApplications :many
SELECT a.id, a.match_id, a.applicant_team_id, a.introduction, a.status, a.created_by_user_id, a.selected_at, a.withdrawn_at, a.created_at, a.updated_at, t.name AS applicant_team_name
FROM match_team_applications a
JOIN teams t ON t.id = a.applicant_team_id
WHERE a.match_id = $1
ORDER BY
    CASE a.status
        WHEN 'selected' THEN 0
        WHEN 'pending' THEN 1
        WHEN 'withdrawn' THEN 2
        ELSE 3
    END,
    a.created_at,
    a.id
`

type ListTeamApplicationsRow struct {
	ID                pgtype.UUID      `json:"id"`
	MatchID           pgtype.UUID      `json:"match_id"`
	ApplicantTeamID   int64            `json:"applicant_team_id"`
	Introduction      string           `json:"introduction"`
	Status            string           `json:"status"`
	CreatedByUserID   int64            `json:"created_by_user_id"`
	SelectedAt        pgtype.Timestamp `json:"selected_at"`
	WithdrawnAt       pgtype.Timestamp `json:"withdrawn_at"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	ApplicantTeamName string           `json:"applicant_team_name"`
}

func (q *Queries) ListTeamApplications(ctx context.Context, matchID pgtype.UUID) ([]ListTeamApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listTeamApplications, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamApplicationsRow
	for rows.Next() {
		var i ListTeamApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.ApplicantTeamID,
			&i.Introduction,
			&i.Status,
			&i.CreatedByUserID,
			&i.SelectedAt,
			&i.WithdrawnAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ApplicantTeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamApplicationsForManager = `-- name: ListTeamApplicationsForManager :many
SELECT a.id, a.match_id, a.applicant_team_id, a.introduction, a.status, a.created_by_user_id, a.selected_at, a.withdrawn_at, a.created_at, a.updated_at, t.name AS applicant_team_name
FROM match_team_applications a
JOIN teams t ON t.id = a.applicant_team_id
JOIN team_members tm
  ON tm.team_id = a.applicant_team_id
 AND tm.user_id = $1
 AND tm.status = 'active'
 AND tm.role IN ('captain', 'leader')
WHERE a.match_id = $2
ORDER BY a.created_at, a.id
`

type ListTeamApplicationsForManagerParams struct {
	UserID  int64       `json:"user_id"`
	MatchID pgtype.UUID `json:"match_id"`
}

type ListTeamApplicationsForManagerRow struct {
	ID                pgtype.UUID      `json:"id"`
	MatchID           pgtype.UUID      `json:"match_id"`
	ApplicantTeamID   int64            `json:"applicant_team_id"`
	Introduction      string           `json:"introduction"`
	Status            string           `json:"status"`
	CreatedByUserID   int64            `json:"created_by_user_id"`
	SelectedAt        pgtype.Timestamp `json:"selected_at"`
	WithdrawnAt       pgtype.Timestamp `json:"withdrawn_at"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	ApplicantTeamName string           `json:"applicant_team_name"`
}

func (q *Queries) ListTeamApplicationsForManager(ctx context.Context, arg ListTeamApplicationsForManagerParams) ([]ListTeamApplicationsForManagerRow, error) {
	rows, err := q.db.Query(ctx, listTeamApplicationsForManager, arg.UserID, arg.MatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamApplicationsForManagerRow
	for rows.Next() {
		var i ListTeamApplicationsForManagerRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.ApplicantTeamID,
			&i.Introduction,
			&i.Status,
			&i.CreatedByUserID,
			&i.SelectedAt,
			&i.WithdrawnAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ApplicantTeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamGroupRoster = `-- name: ListTeamGroupRoster :many
SELECT tm.user_id,
       tm.role AS member_role,
       u.nickname,
       u.avatar_url,
       u.real_name,
       r.status AS registration_status
FROM team_members tm
JOIN users u ON u.id = tm.user_id
LEFT JOIN match_registrations r
    ON r.group_id = $1
   AND r.user_id = tm.user_id
WHERE tm.team_id = $2
ORDER BY
    CASE COALESCE(r.status, 'unregistered')
        WHEN 'attending' THEN 0
        WHEN 'unknown' THEN 1
        WHEN 'unregistered' THEN 2
        WHEN 'leave' THEN 3
        WHEN 'absent' THEN 4
        ELSE 5
    END,
    CASE tm.role
        WHEN 'captain' THEN 0
        WHEN 'leader' THEN 1
        WHEN 'vice_captain' THEN 2
        ELSE 3
    END,
    tm.joined_at,
    tm.user_id
`

type ListTeamGroupRosterParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	TeamID  int64       `json:"team_id"`
}

type ListTeamGroupRosterRow struct {
	UserID             int64   `json:"user_id"`
	MemberRole         string  `json:"member_role"`
	Nickname           string  `json:"nickname"`
	AvatarUrl          *string `json:"avatar_url"`
	RealName           *string `json:"real_name"`
	RegistrationStatus *string `json:"registration_status"`
}

func (q *Queries) ListTeamGroupRoster(ctx context.Context, arg ListTeamGroupRosterParams) ([]ListTeamGroupRosterRow, error) {
	rows, err := q.db.Query(ctx, listTeamGroupRoster, arg.GroupID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamGroupRosterRow
	for rows.Next() {
		var i ListTeamGroupRosterRow
		if err := rows.Scan(
			&i.UserID,
			&i.MemberRole,
			&i.Nickname,
			&i.AvatarUrl,
			&i.RealName,
			&i.RegistrationStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveUserRegistration = `-- name: SaveUserRegistration :exec
INSERT INTO match_registrations (
    id,
    group_id,
    user_id,
    status,
    registration_count,
    created_at,
    updated_at,
    cancelled_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (group_id, user_id) DO UPDATE
SET status = EXCLUDED.status,
    registration_count = EXCLUDED.registration_count,
    updated_at = EXCLUDED.updated_at,
    cancelled_at = EXCLUDED.cancelled_at
`

type SaveUserRegistrationParams struct {
	ID                pgtype.UUID      `json:"id"`
	GroupID           pgtype.UUID      `json:"group_id"`
	UserID            int64            `json:"user_id"`
	Status            string           `json:"status"`
	RegistrationCount int32            `json:"registration_count"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	CancelledAt       pgtype.Timestamp `json:"cancelled_at"`
}

func (q *Queries) SaveUserRegistration(ctx context.Context, arg SaveUserRegistrationParams) error {
	_, err := q.db.Exec(ctx, saveUserRegistration,
		arg.ID,
		arg.GroupID,
		arg.UserID,
		arg.Status,
		arg.RegistrationCount,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CancelledAt,
	)
	return err
}

const updateMatchDetails = `-- name: UpdateMatchDetails :one
UPDATE matches
SET name = $2,
    start_time = $3,
    end_time = $4,
    registration_start_at = $5,
    registration_end_at = $6,
    location = $7,
    location_latitude = $8,
    location_longitude = $9,
    description = $10,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, publication_mode, opponent_state, status, host_team_id, away_team_id, opponent_name, players_per_team, start_time, end_time, location, location_latitude, location_longitude, description, created_by_user_id, created_at, updated_at, created_by_admin_id, registration_start_at, registration_end_at
`

type UpdateMatchDetailsParams struct {
	ID                  pgtype.UUID      `json:"id"`
	Name                string           `json:"name"`
	StartTime           pgtype.Timestamp `json:"start_time"`
	EndTime             pgtype.Timestamp `json:"end_time"`
	RegistrationStartAt pgtype.Timestamp `json:"registration_start_at"`
	RegistrationEndAt   pgtype.Timestamp `json:"registration_end_at"`
	Location            string           `json:"location"`
	LocationLatitude    *float64         `json:"location_latitude"`
	LocationLongitude   *float64         `json:"location_longitude"`
	Description         *string          `json:"description"`
}

func (q *Queries) UpdateMatchDetails(ctx context.Context, arg UpdateMatchDetailsParams) (Match, error) {
	row := q.db.QueryRow(ctx, updateMatchDetails,
		arg.ID,
		arg.Name,
		arg.StartTime,
		arg.EndTime,
		arg.RegistrationStartAt,
		arg.RegistrationEndAt,
		arg.Location,
		arg.LocationLatitude,
		arg.LocationLongitude,
		arg.Description,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicationMode,
		&i.OpponentState,
		&i.Status,
		&i.HostTeamID,
		&i.AwayTeamID,
		&i.OpponentName,
		&i.PlayersPerTeam,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.LocationLatitude,
		&i.LocationLongitude,
		&i.Description,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByAdminID,
		&i.RegistrationStartAt,
		&i.RegistrationEndAt,
	)
	return i, err
}

const updateMatchOpponent = `-- name: UpdateMatchOpponent :exec
UPDATE matches
SET away_team_id = $2,
    opponent_state = $3,
    updated_at = $4
WHERE id = $1
`

type UpdateMatchOpponentParams struct {
	ID            pgtype.UUID      `json:"id"`
	AwayTeamID    *int64           `json:"away_team_id"`
	OpponentState string           `json:"opponent_state"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateMatchOpponent(ctx context.Context, arg UpdateMatchOpponentParams) error {
	_, err := q.db.Exec(ctx, updateMatchOpponent,
		arg.ID,
		arg.AwayTeamID,
		arg.OpponentState,
		arg.UpdatedAt,
	)
	return err
}

const updateMatchStatus = `-- name: UpdateMatchStatus :one
UPDATE matches
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, publication_mode, opponent_state, status, host_team_id, away_team_id, opponent_name, players_per_team, start_time, end_time, location, location_latitude, location_longitude, description, created_by_user_id, created_at, updated_at, created_by_admin_id, registration_start_at, registration_end_at
`

type UpdateMatchStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateMatchStatus(ctx context.Context, arg UpdateMatchStatusParams) (Match, error) {
	row := q.db.QueryRow(ctx, updateMatchStatus, arg.ID, arg.Status)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicationMode,
		&i.OpponentState,
		&i.Status,
		&i.HostTeamID,
		&i.AwayTeamID,
		&i.OpponentName,
		&i.PlayersPerTeam,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.LocationLatitude,
		&i.LocationLongitude,
		&i.Description,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByAdminID,
		&i.RegistrationStartAt,
		&i.RegistrationEndAt,
	)
	return i, err
}

const updateRegistrationGroupState = `-- name: UpdateRegistrationGroupState :exec
UPDATE match_registration_groups
SET status = $2,
    cancelled_at = $3,
    updated_at = $4
WHERE id = $1
`

type UpdateRegistrationGroupStateParams struct {
	ID          pgtype.UUID      `json:"id"`
	Status      string           `json:"status"`
	CancelledAt pgtype.Timestamp `json:"cancelled_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateRegistrationGroupState(ctx context.Context, arg UpdateRegistrationGroupStateParams) error {
	_, err := q.db.Exec(ctx, updateRegistrationGroupState,
		arg.ID,
		arg.Status,
		arg.CancelledAt,
		arg.UpdatedAt,
	)
	return err
}

const updateTeamApplication = `-- name: UpdateTeamApplication :exec
UPDATE match_team_applications
SET status = $2,
    selected_at = $3,
    withdrawn_at = $4,
    updated_at = $5
WHERE id = $1
`

type UpdateTeamApplicationParams struct {
	ID          pgtype.UUID      `json:"id"`
	Status      string           `json:"status"`
	SelectedAt  pgtype.Timestamp `json:"selected_at"`
	WithdrawnAt pgtype.Timestamp `json:"withdrawn_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateTeamApplication(ctx context.Context, arg UpdateTeamApplicationParams) error {
	_, err := q.db.Exec(ctx, updateTeamApplication,
		arg.ID,
		arg.Status,
		arg.SelectedAt,
		arg.WithdrawnAt,
		arg.UpdatedAt,
	)
	return err
}
