// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: match.sql

package matchsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMatchesForAdmin = `-- name: CountMatchesForAdmin :one
SELECT COUNT(*)
FROM matches m
JOIN teams host ON host.id = m.host_team_id
WHERE ($1::text IS NULL OR m.status = $1)
  AND (
      $2::text = ''
      OR m.name ILIKE '%' || $2 || '%'
      OR m.location ILIKE '%' || $2 || '%'
      OR host.name ILIKE '%' || $2 || '%'
  )
`

type CountMatchesForAdminParams struct {
	Status *string `json:"status"`
	Search string  `json:"search"`
}

func (q *Queries) CountMatchesForAdmin(ctx context.Context, arg CountMatchesForAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMatchesForAdmin, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (
    id,
    name,
    publication_mode,
    opponent_state,
    status,
    host_team_id,
    away_team_id,
    opponent_name,
    players_per_team,
    start_time,
    end_time,
    location,
    location_latitude,
    location_longitude,
    description,
    created_by_user_id,
    created_by_admin_id
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14, $15, $16, $17
)
RETURNING id, name, publication_mode, opponent_state, status, host_team_id, away_team_id, opponent_name, players_per_team, start_time, end_time, location, location_latitude, location_longitude, description, created_by_user_id, created_at, updated_at, created_by_admin_id
`

type CreateMatchParams struct {
	ID                pgtype.UUID      `json:"id"`
	Name              string           `json:"name"`
	PublicationMode   string           `json:"publication_mode"`
	OpponentState     string           `json:"opponent_state"`
	Status            string           `json:"status"`
	HostTeamID        int64            `json:"host_team_id"`
	AwayTeamID        *int64           `json:"away_team_id"`
	OpponentName      *string          `json:"opponent_name"`
	PlayersPerTeam    int32            `json:"players_per_team"`
	StartTime         pgtype.Timestamp `json:"start_time"`
	EndTime           pgtype.Timestamp `json:"end_time"`
	Location          string           `json:"location"`
	LocationLatitude  *float64         `json:"location_latitude"`
	LocationLongitude *float64         `json:"location_longitude"`
	Description       *string          `json:"description"`
	CreatedByUserID   *int64           `json:"created_by_user_id"`
	CreatedByAdminID  *int64           `json:"created_by_admin_id"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, createMatch,
		arg.ID,
		arg.Name,
		arg.PublicationMode,
		arg.OpponentState,
		arg.Status,
		arg.HostTeamID,
		arg.AwayTeamID,
		arg.OpponentName,
		arg.PlayersPerTeam,
		arg.StartTime,
		arg.EndTime,
		arg.Location,
		arg.LocationLatitude,
		arg.LocationLongitude,
		arg.Description,
		arg.CreatedByUserID,
		arg.CreatedByAdminID,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicationMode,
		&i.OpponentState,
		&i.Status,
		&i.HostTeamID,
		&i.AwayTeamID,
		&i.OpponentName,
		&i.PlayersPerTeam,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.LocationLatitude,
		&i.LocationLongitude,
		&i.Description,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByAdminID,
	)
	return i, err
}

const createRegistration = `-- name: CreateRegistration :exec
INSERT INTO match_registrations (
    id,
    group_id,
    user_id,
    status,
    registration_count,
    created_at,
    updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type CreateRegistrationParams struct {
	ID                pgtype.UUID      `json:"id"`
	GroupID           pgtype.UUID      `json:"group_id"`
	UserID            int64            `json:"user_id"`
	Status            string           `json:"status"`
	RegistrationCount int32            `json:"registration_count"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateRegistration(ctx context.Context, arg CreateRegistrationParams) error {
	_, err := q.db.Exec(ctx, createRegistration,
		arg.ID,
		arg.GroupID,
		arg.UserID,
		arg.Status,
		arg.RegistrationCount,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createRegistrationGroup = `-- name: CreateRegistrationGroup :one
INSERT INTO match_registration_groups (
    id,
    match_id,
    kind,
    team_id,
    min_players,
    max_players,
    status
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, match_id, kind, team_id, min_players, max_players, status, created_at, updated_at, cancelled_at
`

type CreateRegistrationGroupParams struct {
	ID         pgtype.UUID `json:"id"`
	MatchID    pgtype.UUID `json:"match_id"`
	Kind       string      `json:"kind"`
	TeamID     *int64      `json:"team_id"`
	MinPlayers *int32      `json:"min_players"`
	MaxPlayers *int32      `json:"max_players"`
	Status     string      `json:"status"`
}

func (q *Queries) CreateRegistrationGroup(ctx context.Context, arg CreateRegistrationGroupParams) (MatchRegistrationGroup, error) {
	row := q.db.QueryRow(ctx, createRegistrationGroup,
		arg.ID,
		arg.MatchID,
		arg.Kind,
		arg.TeamID,
		arg.MinPlayers,
		arg.MaxPlayers,
		arg.Status,
	)
	var i MatchRegistrationGroup
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.Kind,
		&i.TeamID,
		&i.MinPlayers,
		&i.MaxPlayers,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const deleteMatch = `-- name: DeleteMatch :execrows
DELETE FROM matches
WHERE id = $1
`

func (q *Queries) DeleteMatch(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMatch, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMatchByID = `-- name: GetMatchByID :one
SELECT id, name, publication_mode, opponent_state, status, host_team_id, away_team_id, opponent_name, players_per_team, start_time, end_time, location, location_latitude, location_longitude, description, created_by_user_id, created_at, updated_at, created_by_admin_id
FROM matches
WHERE id = $1
`

func (q *Queries) GetMatchByID(ctx context.Context, id pgtype.UUID) (Match, error) {
	row := q.db.QueryRow(ctx, getMatchByID, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicationMode,
		&i.OpponentState,
		&i.Status,
		&i.HostTeamID,
		&i.AwayTeamID,
		&i.OpponentName,
		&i.PlayersPerTeam,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.LocationLatitude,
		&i.LocationLongitude,
		&i.Description,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByAdminID,
	)
	return i, err
}

const getMatchForAdmin = `-- name: GetMatchForAdmin :one
SELECT m.id, m.name, m.publication_mode, m.opponent_state, m.status, m.host_team_id, m.away_team_id, m.opponent_name, m.players_per_team, m.start_time, m.end_time, m.location, m.location_latitude, m.location_longitude, m.description, m.created_by_user_id, m.created_at, m.updated_at, m.created_by_admin_id,
       host.name AS host_team_name,
       away.name AS away_team_name
FROM matches m
JOIN teams host ON host.id = m.host_team_id
LEFT JOIN teams away ON away.id = m.away_team_id
WHERE m.id = $1
`

type GetMatchForAdminRow struct {
	ID                pgtype.UUID      `json:"id"`
	Name              string           `json:"name"`
	PublicationMode   string           `json:"publication_mode"`
	OpponentState     string           `json:"opponent_state"`
	Status            string           `json:"status"`
	HostTeamID        int64            `json:"host_team_id"`
	AwayTeamID        *int64           `json:"away_team_id"`
	OpponentName      *string          `json:"opponent_name"`
	PlayersPerTeam    int32            `json:"players_per_team"`
	StartTime         pgtype.Timestamp `json:"start_time"`
	EndTime           pgtype.Timestamp `json:"end_time"`
	Location          string           `json:"location"`
	LocationLatitude  *float64         `json:"location_latitude"`
	LocationLongitude *float64         `json:"location_longitude"`
	Description       *string          `json:"description"`
	CreatedByUserID   *int64           `json:"created_by_user_id"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	CreatedByAdminID  *int64           `json:"created_by_admin_id"`
	HostTeamName      string           `json:"host_team_name"`
	AwayTeamName      *string          `json:"away_team_name"`
}

func (q *Queries) GetMatchForAdmin(ctx context.Context, id pgtype.UUID) (GetMatchForAdminRow, error) {
	row := q.db.QueryRow(ctx, getMatchForAdmin, id)
	var i GetMatchForAdminRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicationMode,
		&i.OpponentState,
		&i.Status,
		&i.HostTeamID,
		&i.AwayTeamID,
		&i.OpponentName,
		&i.PlayersPerTeam,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.LocationLatitude,
		&i.LocationLongitude,
		&i.Description,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByAdminID,
		&i.HostTeamName,
		&i.AwayTeamName,
	)
	return i, err
}

const listIndividualGroupRegistrations = `-- name: ListIndividualGroupRegistrations :many
SELECT r.user_id,
       u.nickname,
       u.avatar_url,
       u.real_name,
       r.status AS registration_status
FROM match_registrations r
JOIN users u ON u.id = r.user_id
WHERE r.group_id = $1
ORDER BY
    CASE r.status
        WHEN 'attending' THEN 0
        WHEN 'unknown' THEN 1
        WHEN 'leave' THEN 3
        WHEN 'absent' THEN 4
        ELSE 5
    END,
    r.created_at,
    r.user_id
`

type ListIndividualGroupRegistrationsRow struct {
	UserID             int64   `json:"user_id"`
	Nickname           string  `json:"nickname"`
	AvatarUrl          *string `json:"avatar_url"`
	RealName           *string `json:"real_name"`
	RegistrationStatus string  `json:"registration_status"`
}

func (q *Queries) ListIndividualGroupRegistrations(ctx context.Context, groupID pgtype.UUID) ([]ListIndividualGroupRegistrationsRow, error) {
	rows, err := q.db.Query(ctx, listIndividualGroupRegistrations, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIndividualGroupRegistrationsRow
	for rows.Next() {
		var i ListIndividualGroupRegistrationsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Nickname,
			&i.AvatarUrl,
			&i.RealName,
			&i.RegistrationStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesForAdmin = `-- name: ListMatchesForAdmin :many
SELECT m.id, m.name, m.publication_mode, m.opponent_state, m.status, m.host_team_id, m.away_team_id, m.opponent_name, m.players_per_team, m.start_time, m.end_time, m.location, m.location_latitude, m.location_longitude, m.description, m.created_by_user_id, m.created_at, m.updated_at, m.created_by_admin_id,
       host.name AS host_team_name,
       away.name AS away_team_name
FROM matches m
JOIN teams host ON host.id = m.host_team_id
LEFT JOIN teams away ON away.id = m.away_team_id
WHERE ($1::text IS NULL OR m.status = $1)
  AND (
      $2::text = ''
      OR m.name ILIKE '%' || $2 || '%'
      OR m.location ILIKE '%' || $2 || '%'
      OR host.name ILIKE '%' || $2 || '%'
  )
ORDER BY m.start_time DESC, m.id
LIMIT $4 OFFSET $3
`

type ListMatchesForAdminParams struct {
	Status      *string `json:"status"`
	Search      string  `json:"search"`
	OffsetCount int32   `json:"offset_count"`
	LimitCount  int32   `json:"limit_count"`
}

type ListMatchesForAdminRow struct {
	ID                pgtype.UUID      `json:"id"`
	Name              string           `json:"name"`
	PublicationMode   string           `json:"publication_mode"`
	OpponentState     string           `json:"opponent_state"`
	Status            string           `json:"status"`
	HostTeamID        int64            `json:"host_team_id"`
	AwayTeamID        *int64           `json:"away_team_id"`
	OpponentName      *string          `json:"opponent_name"`
	PlayersPerTeam    int32            `json:"players_per_team"`
	StartTime         pgtype.Timestamp `json:"start_time"`
	EndTime           pgtype.Timestamp `json:"end_time"`
	Location          string           `json:"location"`
	LocationLatitude  *float64         `json:"location_latitude"`
	LocationLongitude *float64         `json:"location_longitude"`
	Description       *string          `json:"description"`
	CreatedByUserID   *int64           `json:"created_by_user_id"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	CreatedByAdminID  *int64           `json:"created_by_admin_id"`
	HostTeamName      string           `json:"host_team_name"`
	AwayTeamName      *string          `json:"away_team_name"`
}

func (q *Queries) ListMatchesForAdmin(ctx context.Context, arg ListMatchesForAdminParams) ([]ListMatchesForAdminRow, error) {
	rows, err := q.db.Query(ctx, listMatchesForAdmin,
		arg.Status,
		arg.Search,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchesForAdminRow
	for rows.Next() {
		var i ListMatchesForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PublicationMode,
			&i.OpponentState,
			&i.Status,
			&i.HostTeamID,
			&i.AwayTeamID,
			&i.OpponentName,
			&i.PlayersPerTeam,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
			&i.LocationLatitude,
			&i.LocationLongitude,
			&i.Description,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByAdminID,
			&i.HostTeamName,
			&i.AwayTeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistrationGroupsByMatchID = `-- name: ListRegistrationGroupsByMatchID :many
SELECT id, match_id, kind, team_id, min_players, max_players, status, created_at, updated_at, cancelled_at
FROM match_registration_groups
WHERE match_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListRegistrationGroupsByMatchID(ctx context.Context, matchID pgtype.UUID) ([]MatchRegistrationGroup, error) {
	rows, err := q.db.Query(ctx, listRegistrationGroupsByMatchID, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MatchRegistrationGroup
	for rows.Next() {
		var i MatchRegistrationGroup
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.Kind,
			&i.TeamID,
			&i.MinPlayers,
			&i.MaxPlayers,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamGroupRoster = `-- name: ListTeamGroupRoster :many
SELECT tm.user_id,
       tm.role AS member_role,
       u.nickname,
       u.avatar_url,
       u.real_name,
       r.status AS registration_status
FROM team_members tm
JOIN users u ON u.id = tm.user_id
LEFT JOIN match_registrations r
    ON r.group_id = $1
   AND r.user_id = tm.user_id
WHERE tm.team_id = $2
ORDER BY
    CASE COALESCE(r.status, 'unregistered')
        WHEN 'attending' THEN 0
        WHEN 'unknown' THEN 1
        WHEN 'unregistered' THEN 2
        WHEN 'leave' THEN 3
        WHEN 'absent' THEN 4
        ELSE 5
    END,
    CASE tm.role
        WHEN 'captain' THEN 0
        WHEN 'leader' THEN 1
        WHEN 'vice_captain' THEN 2
        ELSE 3
    END,
    tm.joined_at,
    tm.user_id
`

type ListTeamGroupRosterParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	TeamID  int64       `json:"team_id"`
}

type ListTeamGroupRosterRow struct {
	UserID             int64   `json:"user_id"`
	MemberRole         string  `json:"member_role"`
	Nickname           string  `json:"nickname"`
	AvatarUrl          *string `json:"avatar_url"`
	RealName           *string `json:"real_name"`
	RegistrationStatus *string `json:"registration_status"`
}

func (q *Queries) ListTeamGroupRoster(ctx context.Context, arg ListTeamGroupRosterParams) ([]ListTeamGroupRosterRow, error) {
	rows, err := q.db.Query(ctx, listTeamGroupRoster, arg.GroupID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamGroupRosterRow
	for rows.Next() {
		var i ListTeamGroupRosterRow
		if err := rows.Scan(
			&i.UserID,
			&i.MemberRole,
			&i.Nickname,
			&i.AvatarUrl,
			&i.RealName,
			&i.RegistrationStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMatchDetails = `-- name: UpdateMatchDetails :one
UPDATE matches
SET name = $2,
    start_time = $3,
    end_time = $4,
    location = $5,
    location_latitude = $6,
    location_longitude = $7,
    description = $8,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, publication_mode, opponent_state, status, host_team_id, away_team_id, opponent_name, players_per_team, start_time, end_time, location, location_latitude, location_longitude, description, created_by_user_id, created_at, updated_at, created_by_admin_id
`

type UpdateMatchDetailsParams struct {
	ID                pgtype.UUID      `json:"id"`
	Name              string           `json:"name"`
	StartTime         pgtype.Timestamp `json:"start_time"`
	EndTime           pgtype.Timestamp `json:"end_time"`
	Location          string           `json:"location"`
	LocationLatitude  *float64         `json:"location_latitude"`
	LocationLongitude *float64         `json:"location_longitude"`
	Description       *string          `json:"description"`
}

func (q *Queries) UpdateMatchDetails(ctx context.Context, arg UpdateMatchDetailsParams) (Match, error) {
	row := q.db.QueryRow(ctx, updateMatchDetails,
		arg.ID,
		arg.Name,
		arg.StartTime,
		arg.EndTime,
		arg.Location,
		arg.LocationLatitude,
		arg.LocationLongitude,
		arg.Description,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicationMode,
		&i.OpponentState,
		&i.Status,
		&i.HostTeamID,
		&i.AwayTeamID,
		&i.OpponentName,
		&i.PlayersPerTeam,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.LocationLatitude,
		&i.LocationLongitude,
		&i.Description,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByAdminID,
	)
	return i, err
}

const updateMatchStatus = `-- name: UpdateMatchStatus :one
UPDATE matches
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, publication_mode, opponent_state, status, host_team_id, away_team_id, opponent_name, players_per_team, start_time, end_time, location, location_latitude, location_longitude, description, created_by_user_id, created_at, updated_at, created_by_admin_id
`

type UpdateMatchStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateMatchStatus(ctx context.Context, arg UpdateMatchStatusParams) (Match, error) {
	row := q.db.QueryRow(ctx, updateMatchStatus, arg.ID, arg.Status)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicationMode,
		&i.OpponentState,
		&i.Status,
		&i.HostTeamID,
		&i.AwayTeamID,
		&i.OpponentName,
		&i.PlayersPerTeam,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.LocationLatitude,
		&i.LocationLongitude,
		&i.Description,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByAdminID,
	)
	return i, err
}
