// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system.sql

package systemsqlc

import (
	"context"
)

const getMatchRegistrationDefault = `-- name: GetMatchRegistrationDefault :one
SELECT players_per_team, min_players, max_players, updated_by_admin_id, created_at, updated_at
FROM match_registration_defaults
WHERE players_per_team = $1
`

func (q *Queries) GetMatchRegistrationDefault(ctx context.Context, playersPerTeam int32) (MatchRegistrationDefault, error) {
	row := q.db.QueryRow(ctx, getMatchRegistrationDefault, playersPerTeam)
	var i MatchRegistrationDefault
	err := row.Scan(
		&i.PlayersPerTeam,
		&i.MinPlayers,
		&i.MaxPlayers,
		&i.UpdatedByAdminID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMatchRegistrationDefaults = `-- name: ListMatchRegistrationDefaults :many
SELECT players_per_team, min_players, max_players, updated_by_admin_id, created_at, updated_at
FROM match_registration_defaults
ORDER BY players_per_team
`

func (q *Queries) ListMatchRegistrationDefaults(ctx context.Context) ([]MatchRegistrationDefault, error) {
	rows, err := q.db.Query(ctx, listMatchRegistrationDefaults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MatchRegistrationDefault
	for rows.Next() {
		var i MatchRegistrationDefault
		if err := rows.Scan(
			&i.PlayersPerTeam,
			&i.MinPlayers,
			&i.MaxPlayers,
			&i.UpdatedByAdminID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMatchRegistrationDefault = `-- name: UpsertMatchRegistrationDefault :one
INSERT INTO match_registration_defaults (
    players_per_team,
    min_players,
    max_players,
    updated_by_admin_id
)
VALUES ($1, $2, $3, $4)
ON CONFLICT (players_per_team) DO UPDATE
SET min_players = EXCLUDED.min_players,
    max_players = EXCLUDED.max_players,
    updated_by_admin_id = EXCLUDED.updated_by_admin_id,
    updated_at = NOW()
RETURNING players_per_team, min_players, max_players, updated_by_admin_id, created_at, updated_at
`

type UpsertMatchRegistrationDefaultParams struct {
	PlayersPerTeam   int32  `json:"players_per_team"`
	MinPlayers       int32  `json:"min_players"`
	MaxPlayers       int32  `json:"max_players"`
	UpdatedByAdminID *int64 `json:"updated_by_admin_id"`
}

func (q *Queries) UpsertMatchRegistrationDefault(ctx context.Context, arg UpsertMatchRegistrationDefaultParams) (MatchRegistrationDefault, error) {
	row := q.db.QueryRow(ctx, upsertMatchRegistrationDefault,
		arg.PlayersPerTeam,
		arg.MinPlayers,
		arg.MaxPlayers,
		arg.UpdatedByAdminID,
	)
	var i MatchRegistrationDefault
	err := row.Scan(
		&i.PlayersPerTeam,
		&i.MinPlayers,
		&i.MaxPlayers,
		&i.UpdatedByAdminID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
