// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: minireview.sql

package minireviewsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMiniReviewStatuses = `-- name: CountMiniReviewStatuses :one
SELECT COUNT(*)
FROM mini_review_statuses
WHERE project_code = COALESCE($1, project_code)
`

func (q *Queries) CountMiniReviewStatuses(ctx context.Context, projectCode *string) (int64, error) {
	row := q.db.QueryRow(ctx, countMiniReviewStatuses, projectCode)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMiniReviewStatus = `-- name: CreateMiniReviewStatus :one
INSERT INTO mini_review_statuses (project_code, version, version_code, is_reviewing, status_text)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_code, version, version_code, is_reviewing, status_text, created_at, updated_at
`

type CreateMiniReviewStatusParams struct {
	ProjectCode string `json:"project_code"`
	Version     string `json:"version"`
	VersionCode int64  `json:"version_code"`
	IsReviewing bool   `json:"is_reviewing"`
	StatusText  string `json:"status_text"`
}

func (q *Queries) CreateMiniReviewStatus(ctx context.Context, arg CreateMiniReviewStatusParams) (MiniReviewStatus, error) {
	row := q.db.QueryRow(ctx, createMiniReviewStatus,
		arg.ProjectCode,
		arg.Version,
		arg.VersionCode,
		arg.IsReviewing,
		arg.StatusText,
	)
	var i MiniReviewStatus
	err := row.Scan(
		&i.ID,
		&i.ProjectCode,
		&i.Version,
		&i.VersionCode,
		&i.IsReviewing,
		&i.StatusText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestMiniReviewStatus = `-- name: GetLatestMiniReviewStatus :one
SELECT id, project_code, version, version_code, is_reviewing, status_text, created_at, updated_at
FROM mini_review_statuses
WHERE project_code = $1
ORDER BY version_code DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestMiniReviewStatus(ctx context.Context, projectCode string) (MiniReviewStatus, error) {
	row := q.db.QueryRow(ctx, getLatestMiniReviewStatus, projectCode)
	var i MiniReviewStatus
	err := row.Scan(
		&i.ID,
		&i.ProjectCode,
		&i.Version,
		&i.VersionCode,
		&i.IsReviewing,
		&i.StatusText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMiniReviewStatusByID = `-- name: GetMiniReviewStatusByID :one
SELECT id, project_code, version, version_code, is_reviewing, status_text, created_at, updated_at
FROM mini_review_statuses
WHERE id = $1
`

func (q *Queries) GetMiniReviewStatusByID(ctx context.Context, id int64) (MiniReviewStatus, error) {
	row := q.db.QueryRow(ctx, getMiniReviewStatusByID, id)
	var i MiniReviewStatus
	err := row.Scan(
		&i.ID,
		&i.ProjectCode,
		&i.Version,
		&i.VersionCode,
		&i.IsReviewing,
		&i.StatusText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMiniReviewStatusByProjectAndVersion = `-- name: GetMiniReviewStatusByProjectAndVersion :one
SELECT id, project_code, version, version_code, is_reviewing, status_text, created_at, updated_at
FROM mini_review_statuses
WHERE project_code = $1
  AND version = $2
`

type GetMiniReviewStatusByProjectAndVersionParams struct {
	ProjectCode string `json:"project_code"`
	Version     string `json:"version"`
}

func (q *Queries) GetMiniReviewStatusByProjectAndVersion(ctx context.Context, arg GetMiniReviewStatusByProjectAndVersionParams) (MiniReviewStatus, error) {
	row := q.db.QueryRow(ctx, getMiniReviewStatusByProjectAndVersion, arg.ProjectCode, arg.Version)
	var i MiniReviewStatus
	err := row.Scan(
		&i.ID,
		&i.ProjectCode,
		&i.Version,
		&i.VersionCode,
		&i.IsReviewing,
		&i.StatusText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMiniReviewStatuses = `-- name: ListMiniReviewStatuses :many
SELECT id, project_code, version, version_code, is_reviewing, status_text, created_at, updated_at
FROM mini_review_statuses
WHERE project_code = COALESCE($1, project_code)
ORDER BY updated_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListMiniReviewStatusesParams struct {
	ProjectCode *string `json:"project_code"`
	OffsetRows  int32   `json:"offset_rows"`
	LimitRows   int32   `json:"limit_rows"`
}

func (q *Queries) ListMiniReviewStatuses(ctx context.Context, arg ListMiniReviewStatusesParams) ([]MiniReviewStatus, error) {
	rows, err := q.db.Query(ctx, listMiniReviewStatuses, arg.ProjectCode, arg.OffsetRows, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MiniReviewStatus
	for rows.Next() {
		var i MiniReviewStatus
		if err := rows.Scan(
			&i.ID,
			&i.ProjectCode,
			&i.Version,
			&i.VersionCode,
			&i.IsReviewing,
			&i.StatusText,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMiniReviewStatusState = `-- name: UpdateMiniReviewStatusState :one
UPDATE mini_review_statuses
SET is_reviewing = $2,
    status_text = $3,
    updated_at = $4
WHERE id = $1
RETURNING id, project_code, version, version_code, is_reviewing, status_text, created_at, updated_at
`

type UpdateMiniReviewStatusStateParams struct {
	ID          int64              `json:"id"`
	IsReviewing bool               `json:"is_reviewing"`
	StatusText  string             `json:"status_text"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateMiniReviewStatusState(ctx context.Context, arg UpdateMiniReviewStatusStateParams) (MiniReviewStatus, error) {
	row := q.db.QueryRow(ctx, updateMiniReviewStatusState,
		arg.ID,
		arg.IsReviewing,
		arg.StatusText,
		arg.UpdatedAt,
	)
	var i MiniReviewStatus
	err := row.Scan(
		&i.ID,
		&i.ProjectCode,
		&i.Version,
		&i.VersionCode,
		&i.IsReviewing,
		&i.StatusText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
