export default [
  { path: "/login", layout: false, component: "./LoginPage" },
  {
    path: "/403",
    name: "无权访问",
    hideInMenu: true,
    component: "./ForbiddenPage",
  },
  {
    path: "/404",
    name: "页面不存在",
    hideInMenu: true,
    component: "./NotFoundPage",
  },
  {
    path: "/",
    access: "isAuthenticated",
    name: "系统概览",
    icon: "DashboardOutlined",
    component: "./DashboardPage",
  },
  {
    path: "/matches",
    access: "isAuthenticated",
    name: "比赛管理",
    icon: "CalendarOutlined",
    component: "./MatchListPage",
  },
  {
    path: "/matches/new",
    access: "isAuthenticated",
    name: "发布比赛",
    hideInMenu: true,
    component: "./MatchFormPage",
  },
  {
    path: "/matches/:id",
    access: "isAuthenticated",
    name: "比赛详情",
    hideInMenu: true,
    component: "./MatchDetailPage",
  },
  {
    path: "/matches/:id/edit",
    access: "isAuthenticated",
    name: "编辑比赛",
    hideInMenu: true,
    component: "./MatchFormPage",
  },
  {
    path: "/teams",
    access: "isAuthenticated",
    name: "球队管理",
    icon: "TeamOutlined",
    component: "./TeamListPage",
  },
  {
    path: "/admins",
    access: "isSuperAdmin",
    name: "场馆管理员",
    icon: "ShopOutlined",
    component: "./AdminListPage",
  },
  {
    path: "/access",
    access: "isAuthenticated",
    name: "接入状态",
    icon: "SafetyCertificateOutlined",
    component: "./AccessPage",
  },
  { path: "/*", component: "./NotFoundPage" },
];
