// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package authsqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (openid, nickname, avatar_url)
VALUES ($1, $2, $3)
RETURNING id, openid, nickname, avatar_url, status, created_at, updated_at
`

type CreateUserParams struct {
	Openid    string  `json:"openid"`
	Nickname  string  `json:"nickname"`
	AvatarUrl *string `json:"avatar_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Openid, arg.Nickname, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Openid,
		&i.Nickname,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, username, password_hash, role, status, created_at, updated_at
FROM admin_users
WHERE id = $1
`

func (q *Queries) GetAdminByID(ctx context.Context, id int64) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByUsername = `-- name: GetAdminByUsername :one
SELECT id, username, password_hash, role, status, created_at, updated_at
FROM admin_users
WHERE username = $1
`

func (q *Queries) GetAdminByUsername(ctx context.Context, username string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminByUsername, username)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, openid, nickname, avatar_url, status, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Openid,
		&i.Nickname,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByOpenID = `-- name: GetUserByOpenID :one
SELECT id, openid, nickname, avatar_url, status, created_at, updated_at
FROM users
WHERE openid = $1
`

func (q *Queries) GetUserByOpenID(ctx context.Context, openid string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByOpenID, openid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Openid,
		&i.Nickname,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET nickname = $2,
    avatar_url = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, openid, nickname, avatar_url, status, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID        int64   `json:"id"`
	Nickname  string  `json:"nickname"`
	AvatarUrl *string `json:"avatar_url"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.Nickname, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Openid,
		&i.Nickname,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
