// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package authsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAdmins = `-- name: CountAdmins :one
SELECT COUNT(*) FROM admin_users
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admin_users (username, password_hash, role, status)
VALUES ($1, $2, $3, $4)
RETURNING id, username, password_hash, role, status, created_at, updated_at
`

type CreateAdminParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
	Status       string `json:"status"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, createAdmin,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.Status,
	)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (openid, nickname, avatar_url)
VALUES ($1, $2, $3)
RETURNING id, openid, nickname, avatar_url, real_name, phone_number, status, created_at, updated_at
`

type CreateUserParams struct {
	Openid    string  `json:"openid"`
	Nickname  string  `json:"nickname"`
	AvatarUrl *string `json:"avatar_url"`
}

type CreateUserRow struct {
	ID          int64            `json:"id"`
	Openid      string           `json:"openid"`
	Nickname    string           `json:"nickname"`
	AvatarUrl   *string          `json:"avatar_url"`
	RealName    *string          `json:"real_name"`
	PhoneNumber *string          `json:"phone_number"`
	Status      string           `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Openid, arg.Nickname, arg.AvatarUrl)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Openid,
		&i.Nickname,
		&i.AvatarUrl,
		&i.RealName,
		&i.PhoneNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, username, password_hash, role, status, created_at, updated_at
FROM admin_users
WHERE id = $1
`

func (q *Queries) GetAdminByID(ctx context.Context, id int64) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByUsername = `-- name: GetAdminByUsername :one
SELECT id, username, password_hash, role, status, created_at, updated_at
FROM admin_users
WHERE username = $1
`

func (q *Queries) GetAdminByUsername(ctx context.Context, username string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminByUsername, username)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, openid, nickname, avatar_url, real_name, phone_number, status, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID          int64            `json:"id"`
	Openid      string           `json:"openid"`
	Nickname    string           `json:"nickname"`
	AvatarUrl   *string          `json:"avatar_url"`
	RealName    *string          `json:"real_name"`
	PhoneNumber *string          `json:"phone_number"`
	Status      string           `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Openid,
		&i.Nickname,
		&i.AvatarUrl,
		&i.RealName,
		&i.PhoneNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByOpenID = `-- name: GetUserByOpenID :one
SELECT id, openid, nickname, avatar_url, real_name, phone_number, status, created_at, updated_at
FROM users
WHERE openid = $1
`

type GetUserByOpenIDRow struct {
	ID          int64            `json:"id"`
	Openid      string           `json:"openid"`
	Nickname    string           `json:"nickname"`
	AvatarUrl   *string          `json:"avatar_url"`
	RealName    *string          `json:"real_name"`
	PhoneNumber *string          `json:"phone_number"`
	Status      string           `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetUserByOpenID(ctx context.Context, openid string) (GetUserByOpenIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByOpenID, openid)
	var i GetUserByOpenIDRow
	err := row.Scan(
		&i.ID,
		&i.Openid,
		&i.Nickname,
		&i.AvatarUrl,
		&i.RealName,
		&i.PhoneNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveTestLoginUsers = `-- name: ListActiveTestLoginUsers :many
SELECT u.id,
       u.openid,
       u.nickname,
       u.avatar_url,
       u.real_name,
       u.phone_number,
       u.status,
       u.created_at,
       u.updated_at,
       t.id AS team_id,
       t.name AS team_name,
       tm.role AS team_role
FROM users u
LEFT JOIN team_members tm ON tm.user_id = u.id AND tm.status = 'active'
LEFT JOIN teams t ON t.id = tm.team_id AND t.status = 'active'
WHERE u.status = 'active'
ORDER BY u.id, t.id
`

type ListActiveTestLoginUsersRow struct {
	ID          int64            `json:"id"`
	Openid      string           `json:"openid"`
	Nickname    string           `json:"nickname"`
	AvatarUrl   *string          `json:"avatar_url"`
	RealName    *string          `json:"real_name"`
	PhoneNumber *string          `json:"phone_number"`
	Status      string           `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	TeamID      *int64           `json:"team_id"`
	TeamName    *string          `json:"team_name"`
	TeamRole    *string          `json:"team_role"`
}

func (q *Queries) ListActiveTestLoginUsers(ctx context.Context) ([]ListActiveTestLoginUsersRow, error) {
	rows, err := q.db.Query(ctx, listActiveTestLoginUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveTestLoginUsersRow
	for rows.Next() {
		var i ListActiveTestLoginUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Openid,
			&i.Nickname,
			&i.AvatarUrl,
			&i.RealName,
			&i.PhoneNumber,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TeamID,
			&i.TeamName,
			&i.TeamRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdmins = `-- name: ListAdmins :many
SELECT id, username, password_hash, role, status, created_at, updated_at
FROM admin_users
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListAdmins(ctx context.Context) ([]AdminUser, error) {
	rows, err := q.db.Query(ctx, listAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminUser
	for rows.Next() {
		var i AdminUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserAppProfile = `-- name: UpdateUserAppProfile :one
UPDATE users
SET nickname = $2,
    real_name = $3,
    avatar_url = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, openid, nickname, avatar_url, real_name, phone_number, status, created_at, updated_at
`

type UpdateUserAppProfileParams struct {
	ID        int64   `json:"id"`
	Nickname  string  `json:"nickname"`
	RealName  *string `json:"real_name"`
	AvatarUrl *string `json:"avatar_url"`
}

type UpdateUserAppProfileRow struct {
	ID          int64            `json:"id"`
	Openid      string           `json:"openid"`
	Nickname    string           `json:"nickname"`
	AvatarUrl   *string          `json:"avatar_url"`
	RealName    *string          `json:"real_name"`
	PhoneNumber *string          `json:"phone_number"`
	Status      string           `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateUserAppProfile(ctx context.Context, arg UpdateUserAppProfileParams) (UpdateUserAppProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserAppProfile,
		arg.ID,
		arg.Nickname,
		arg.RealName,
		arg.AvatarUrl,
	)
	var i UpdateUserAppProfileRow
	err := row.Scan(
		&i.ID,
		&i.Openid,
		&i.Nickname,
		&i.AvatarUrl,
		&i.RealName,
		&i.PhoneNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserBasicProfile = `-- name: UpdateUserBasicProfile :one
UPDATE users
SET real_name = $2,
    phone_number = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, openid, nickname, avatar_url, real_name, phone_number, status, created_at, updated_at
`

type UpdateUserBasicProfileParams struct {
	ID          int64   `json:"id"`
	RealName    *string `json:"real_name"`
	PhoneNumber *string `json:"phone_number"`
}

type UpdateUserBasicProfileRow struct {
	ID          int64            `json:"id"`
	Openid      string           `json:"openid"`
	Nickname    string           `json:"nickname"`
	AvatarUrl   *string          `json:"avatar_url"`
	RealName    *string          `json:"real_name"`
	PhoneNumber *string          `json:"phone_number"`
	Status      string           `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateUserBasicProfile(ctx context.Context, arg UpdateUserBasicProfileParams) (UpdateUserBasicProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserBasicProfile, arg.ID, arg.RealName, arg.PhoneNumber)
	var i UpdateUserBasicProfileRow
	err := row.Scan(
		&i.ID,
		&i.Openid,
		&i.Nickname,
		&i.AvatarUrl,
		&i.RealName,
		&i.PhoneNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET nickname = $2,
    avatar_url = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, openid, nickname, avatar_url, real_name, phone_number, status, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID        int64   `json:"id"`
	Nickname  string  `json:"nickname"`
	AvatarUrl *string `json:"avatar_url"`
}

type UpdateUserProfileRow struct {
	ID          int64            `json:"id"`
	Openid      string           `json:"openid"`
	Nickname    string           `json:"nickname"`
	AvatarUrl   *string          `json:"avatar_url"`
	RealName    *string          `json:"real_name"`
	PhoneNumber *string          `json:"phone_number"`
	Status      string           `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.Nickname, arg.AvatarUrl)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Openid,
		&i.Nickname,
		&i.AvatarUrl,
		&i.RealName,
		&i.PhoneNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
