// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team.sql

package teamsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name, description, status)
VALUES ($1, $2, 'active')
RETURNING id, name, description, logo_url, captain_id, status, created_at, updated_at
`

type CreateTeamParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.Name, arg.Description)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.CaptainID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveTeamMember = `-- name: GetActiveTeamMember :one
SELECT id, team_id, user_id, role, status, joined_at, created_at, updated_at
FROM team_members
WHERE team_id = $1
  AND user_id = $2
  AND status = 'active'
`

type GetActiveTeamMemberParams struct {
	TeamID int64 `json:"team_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetActiveTeamMember(ctx context.Context, arg GetActiveTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, getActiveTeamMember, arg.TeamID, arg.UserID)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, description, logo_url, captain_id, status, created_at, updated_at
FROM teams
WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id int64) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.CaptainID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveTeams = `-- name: ListActiveTeams :many
SELECT id, name, description, logo_url, captain_id, status, created_at, updated_at
FROM teams
WHERE status = 'active'
ORDER BY name, id
`

func (q *Queries) ListActiveTeams(ctx context.Context) ([]Team, error) {
	rows, err := q.db.Query(ctx, listActiveTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LogoUrl,
			&i.CaptainID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveUserTeams = `-- name: ListActiveUserTeams :many
SELECT t.id,
       t.name,
       t.description,
       t.logo_url,
       t.captain_id,
       t.status,
       tm.role AS member_role,
       tm.joined_at,
       t.created_at,
       t.updated_at
FROM team_members tm
JOIN teams t ON t.id = tm.team_id
WHERE tm.user_id = $1
  AND tm.status = 'active'
  AND t.status = 'active'
ORDER BY tm.joined_at DESC, t.id
`

type ListActiveUserTeamsRow struct {
	ID          int64            `json:"id"`
	Name        string           `json:"name"`
	Description *string          `json:"description"`
	LogoUrl     *string          `json:"logo_url"`
	CaptainID   *int64           `json:"captain_id"`
	Status      string           `json:"status"`
	MemberRole  string           `json:"member_role"`
	JoinedAt    pgtype.Timestamp `json:"joined_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListActiveUserTeams(ctx context.Context, userID int64) ([]ListActiveUserTeamsRow, error) {
	rows, err := q.db.Query(ctx, listActiveUserTeams, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveUserTeamsRow
	for rows.Next() {
		var i ListActiveUserTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LogoUrl,
			&i.CaptainID,
			&i.Status,
			&i.MemberRole,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
