// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team.sql

package teamsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTeamMember = `-- name: AddTeamMember :one
INSERT INTO team_members (team_id, user_id, role, status)
VALUES ($1, $2, $3, 'active')
RETURNING id, team_id, user_id, role, status, joined_at, created_at, updated_at
`

type AddTeamMemberParams struct {
	TeamID int64  `json:"team_id"`
	UserID int64  `json:"user_id"`
	Role   string `json:"role"`
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, addTeamMember, arg.TeamID, arg.UserID, arg.Role)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clearTeamCaptain = `-- name: ClearTeamCaptain :one
WITH demoted AS (
    UPDATE team_members AS tm
    SET role = 'member',
        updated_at = NOW()
    WHERE tm.team_id = $1
      AND tm.role = 'captain'
)
UPDATE teams
SET captain_id = NULL,
    updated_at = NOW()
WHERE teams.id = $1
RETURNING teams.id, teams.name, teams.description, teams.logo_url, teams.captain_id, teams.status, teams.created_at, teams.updated_at
`

func (q *Queries) ClearTeamCaptain(ctx context.Context, id int64) (Team, error) {
	row := q.db.QueryRow(ctx, clearTeamCaptain, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.CaptainID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name, description, status)
VALUES ($1, $2, 'active')
RETURNING teams.id, teams.name, teams.description, teams.logo_url, teams.captain_id, teams.status, teams.created_at, teams.updated_at
`

type CreateTeamParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.Name, arg.Description)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.CaptainID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :execrows
DELETE FROM teams
WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTeam, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveTeamMember = `-- name: GetActiveTeamMember :one
SELECT id, team_id, user_id, role, status, joined_at, created_at, updated_at
FROM team_members
WHERE team_id = $1
  AND user_id = $2
  AND status = 'active'
`

type GetActiveTeamMemberParams struct {
	TeamID int64 `json:"team_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetActiveTeamMember(ctx context.Context, arg GetActiveTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, getActiveTeamMember, arg.TeamID, arg.UserID)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, description, logo_url, captain_id, status, created_at, updated_at
FROM teams
WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id int64) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.CaptainID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveUserTeams = `-- name: ListActiveUserTeams :many
SELECT t.id,
       t.name,
       t.description,
       t.logo_url,
       t.captain_id,
       t.status,
       tm.role AS member_role,
       tm.joined_at,
       t.created_at,
       t.updated_at
FROM team_members tm
JOIN teams t ON t.id = tm.team_id
WHERE tm.user_id = $1
  AND tm.status = 'active'
  AND t.status = 'active'
ORDER BY tm.joined_at DESC, t.id
`

type ListActiveUserTeamsRow struct {
	ID          int64            `json:"id"`
	Name        string           `json:"name"`
	Description *string          `json:"description"`
	LogoUrl     *string          `json:"logo_url"`
	CaptainID   *int64           `json:"captain_id"`
	Status      string           `json:"status"`
	MemberRole  string           `json:"member_role"`
	JoinedAt    pgtype.Timestamp `json:"joined_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListActiveUserTeams(ctx context.Context, userID int64) ([]ListActiveUserTeamsRow, error) {
	rows, err := q.db.Query(ctx, listActiveUserTeams, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveUserTeamsRow
	for rows.Next() {
		var i ListActiveUserTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LogoUrl,
			&i.CaptainID,
			&i.Status,
			&i.MemberRole,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMemberCandidates = `-- name: ListTeamMemberCandidates :many
SELECT u.id, u.nickname, u.avatar_url, u.real_name, u.phone_number
FROM users u
WHERE u.status = 'active'
  AND NOT EXISTS (
      SELECT 1
      FROM team_members tm
      WHERE tm.team_id = $1
        AND tm.user_id = u.id
  )
  AND (
      $2::text = ''
      OR u.nickname ILIKE '%' || $2::text || '%'
      OR u.real_name ILIKE '%' || $2::text || '%'
      OR u.phone_number ILIKE '%' || $2::text || '%'
      OR u.id::text = $2::text
  )
ORDER BY u.nickname, u.id
LIMIT $3
`

type ListTeamMemberCandidatesParams struct {
	TeamID int64  `json:"team_id"`
	Search string `json:"search"`
	Limit  int32  `json:"limit"`
}

type ListTeamMemberCandidatesRow struct {
	ID          int64   `json:"id"`
	Nickname    string  `json:"nickname"`
	AvatarUrl   *string `json:"avatar_url"`
	RealName    *string `json:"real_name"`
	PhoneNumber *string `json:"phone_number"`
}

func (q *Queries) ListTeamMemberCandidates(ctx context.Context, arg ListTeamMemberCandidatesParams) ([]ListTeamMemberCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listTeamMemberCandidates, arg.TeamID, arg.Search, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMemberCandidatesRow
	for rows.Next() {
		var i ListTeamMemberCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Nickname,
			&i.AvatarUrl,
			&i.RealName,
			&i.PhoneNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT tm.id,
       tm.team_id,
       tm.user_id,
       tm.role,
       tm.status,
       tm.joined_at,
       u.nickname,
       u.avatar_url,
       u.real_name,
       u.phone_number
FROM team_members tm
JOIN users u ON u.id = tm.user_id
WHERE tm.team_id = $1
ORDER BY
    CASE tm.status WHEN 'active' THEN 0 ELSE 1 END,
    CASE tm.role
        WHEN 'captain' THEN 0
        WHEN 'leader' THEN 1
        WHEN 'vice_captain' THEN 2
        ELSE 3
    END,
    tm.joined_at,
    tm.user_id
`

type ListTeamMembersRow struct {
	ID          int64            `json:"id"`
	TeamID      int64            `json:"team_id"`
	UserID      int64            `json:"user_id"`
	Role        string           `json:"role"`
	Status      string           `json:"status"`
	JoinedAt    pgtype.Timestamp `json:"joined_at"`
	Nickname    string           `json:"nickname"`
	AvatarUrl   *string          `json:"avatar_url"`
	RealName    *string          `json:"real_name"`
	PhoneNumber *string          `json:"phone_number"`
}

func (q *Queries) ListTeamMembers(ctx context.Context, teamID int64) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMembersRow
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.JoinedAt,
			&i.Nickname,
			&i.AvatarUrl,
			&i.RealName,
			&i.PhoneNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many
SELECT id, name, description, logo_url, captain_id, status, created_at, updated_at
FROM teams
WHERE $1::text IS NULL OR status = $1::text
ORDER BY name, id
`

func (q *Queries) ListTeams(ctx context.Context, status *string) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeams, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LogoUrl,
			&i.CaptainID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamMember = `-- name: RemoveTeamMember :execrows
DELETE FROM team_members
WHERE team_id = $1
  AND user_id = $2
`

type RemoveTeamMemberParams struct {
	TeamID int64 `json:"team_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeTeamMember, arg.TeamID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setTeamCaptain = `-- name: SetTeamCaptain :one
WITH target AS MATERIALIZED (
    SELECT tm.user_id
    FROM team_members tm
    WHERE tm.team_id = $1
      AND tm.user_id = $2
      AND tm.status = 'active'
), demoted AS (
    UPDATE team_members AS tm
    SET role = 'member',
        updated_at = NOW()
    WHERE tm.team_id = $1
      AND tm.role = 'captain'
      AND tm.user_id <> $2
      AND EXISTS (SELECT 1 FROM target)
), promoted AS (
    UPDATE team_members AS tm
    SET role = 'captain',
        updated_at = NOW()
    WHERE tm.team_id = $1
      AND tm.user_id = $2
      AND tm.status = 'active'
      AND EXISTS (SELECT 1 FROM target)
    RETURNING tm.user_id
)
UPDATE teams
SET captain_id = (SELECT user_id FROM promoted),
    updated_at = NOW()
WHERE teams.id = $1
  AND EXISTS (SELECT 1 FROM promoted)
RETURNING teams.id, teams.name, teams.description, teams.logo_url, teams.captain_id, teams.status, teams.created_at, teams.updated_at
`

type SetTeamCaptainParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) SetTeamCaptain(ctx context.Context, arg SetTeamCaptainParams) (Team, error) {
	row := q.db.QueryRow(ctx, setTeamCaptain, arg.ID, arg.UserID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.CaptainID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams
SET name = $2,
    description = $3,
    status = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING teams.id, teams.name, teams.description, teams.logo_url, teams.captain_id, teams.status, teams.created_at, teams.updated_at
`

type UpdateTeamParams struct {
	ID          int64   `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Status      string  `json:"status"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeam,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.CaptainID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTeamMember = `-- name: UpdateTeamMember :execrows
UPDATE team_members
SET role = $3,
    status = $4,
    updated_at = NOW()
WHERE team_id = $1
  AND user_id = $2
`

type UpdateTeamMemberParams struct {
	TeamID int64  `json:"team_id"`
	UserID int64  `json:"user_id"`
	Role   string `json:"role"`
	Status string `json:"status"`
}

func (q *Queries) UpdateTeamMember(ctx context.Context, arg UpdateTeamMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTeamMember,
		arg.TeamID,
		arg.UserID,
		arg.Role,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
